package com.ceix.ehs.model.ws.proxy;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebService(wsdlLocation="https://eguc-dev2.fa.us2.oraclecloud.com/xmlpserver/services/v2/ReportService?wsdl",
  targetNamespace="http://xmlns.oracle.com/oxp/service/v2", name="ReportService")
@XmlSeeAlso(
  { com.ceix.ehs.model.ws.proxy.types.ObjectFactory.class })
public interface ReportService
{
  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplate/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplate/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplate/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateResponse")
  @ResponseWrapper(localName="getTemplateResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetTemplateResponse")
  @RequestWrapper(localName="getTemplate", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetTemplate")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateReturn")
  public byte[] getTemplate(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportResponse")
  @ResponseWrapper(localName="createReportResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.CreateReportResponse")
  @RequestWrapper(localName="createReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.CreateReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="createReportReturn")
  public String createReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportName")
    String reportName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="folderAbsolutePathURL")
    String folderAbsolutePathURL, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="dataModelURL")
    String dataModelURL, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateFileName")
    String templateFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="XLIFFFileName")
    String xliffFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="XLIFFData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="updateFlag")
    boolean updateFlag, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionInSessionResponse")
  @ResponseWrapper(localName="getReportDefinitionInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportDefinitionInSessionResponse")
  @RequestWrapper(localName="getReportDefinitionInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportDefinitionInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getReportDefinitionInSessionReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportDefinition getReportDefinitionInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionInSessionResponse")
  @ResponseWrapper(localName="updateReportDefinitionInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateReportDefinitionInSessionResponse")
  @RequestWrapper(localName="updateReportDefinitionInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateReportDefinitionInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateReportDefinitionInSessionReturn")
  public boolean updateReportDefinitionInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsPath")
    String reportAbsPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="newReportDefn")
    com.ceix.ehs.model.ws.proxy.types.ReportDefinition newReportDefn,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheInSessionResponse")
  @ResponseWrapper(localName="removeObjectFromCacheInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RemoveObjectFromCacheInSessionResponse")
  @RequestWrapper(localName="removeObjectFromCacheInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RemoveObjectFromCacheInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="removeObjectFromCacheInSessionReturn")
  public boolean removeObjectFromCacheInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="objectPath")
    String objectPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportInSessionResponse")
  @ResponseWrapper(localName="updateTemplateForReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateTemplateForReportInSessionResponse")
  @RequestWrapper(localName="updateTemplateForReportInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateTemplateForReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateTemplateForReportInSessionReturn")
  public boolean updateTemplateForReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateName")
    String templateName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParameters/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParameters/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParameters/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersResponse")
  @ResponseWrapper(localName="getReportParametersResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportParametersResponse")
  @RequestWrapper(localName="getReportParameters", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetReportParameters")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getReportParametersReturn")
  public com.ceix.ehs.model.ws.proxy.types.ParamNameValues getReportParameters(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRequest")
    com.ceix.ehs.model.ws.proxy.types.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportResponse")
  @ResponseWrapper(localName="runReportResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RunReportResponse")
  @RequestWrapper(localName="runReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RunReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="runReportReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportResponse runReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRequest")
    com.ceix.ehs.model.ws.proxy.types.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocales/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocales/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocales/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesResponse")
  @ResponseWrapper(localName="getTemplateAvailableLocalesResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableLocalesResponse")
  @RequestWrapper(localName="getTemplateAvailableLocales",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableLocales")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateAvailableLocalesReturn")
  public List<String> getTemplateAvailableLocales(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/runReportInSessionResponse")
  @ResponseWrapper(localName="runReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RunReportInSessionResponse")
  @RequestWrapper(localName="runReportInSession", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RunReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="runReportInSessionReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportResponse runReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRequest")
    com.ceix.ehs.model.ws.proxy.types.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModel/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModel/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModel/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelResponse")
  @ResponseWrapper(localName="runDataModelResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RunDataModelResponse")
  @RequestWrapper(localName="runDataModel", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RunDataModel")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="runDataModelReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportResponse runDataModel(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRequest")
    com.ceix.ehs.model.ws.proxy.types.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/runDataModelInSessionResponse")
  @ResponseWrapper(localName="runDataModelInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RunDataModelInSessionResponse")
  @RequestWrapper(localName="runDataModelInSession", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RunDataModelInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="runDataModelInSessionReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportResponse runDataModelInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRequest")
    com.ceix.ehs.model.ws.proxy.types.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinition/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinition/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinition/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportDefinitionResponse")
  @ResponseWrapper(localName="getReportDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportDefinitionResponse")
  @RequestWrapper(localName="getReportDefinition", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetReportDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getReportDefinitionReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportDefinition getReportDefinition(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinition/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinition/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinition/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionResponse")
  @ResponseWrapper(localName="getMobileAppDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetMobileAppDefinitionResponse")
  @RequestWrapper(localName="getMobileAppDefinition", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetMobileAppDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getMobileAppDefinitionReturn")
  public com.ceix.ehs.model.ws.proxy.types.MobileAppDefinition getMobileAppDefinition(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getMobileAppDefinitionInSessionResponse")
  @ResponseWrapper(localName="getMobileAppDefinitionInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetMobileAppDefinitionInSessionResponse")
  @RequestWrapper(localName="getMobileAppDefinitionInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetMobileAppDefinitionInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getMobileAppDefinitionInSessionReturn")
  public com.ceix.ehs.model.ws.proxy.types.MobileAppDefinition getMobileAppDefinitionInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleData/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleData/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleData/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataResponse")
  @ResponseWrapper(localName="getReportSampleDataResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportSampleDataResponse")
  @RequestWrapper(localName="getReportSampleData", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetReportSampleData")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getReportSampleDataReturn")
  public byte[] getReportSampleData(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportSampleDataInSessionResponse")
  @ResponseWrapper(localName="getReportSampleDataInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportSampleDataInSessionResponse")
  @RequestWrapper(localName="getReportSampleDataInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportSampleDataInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getReportSampleDataInSessionReturn")
  public byte[] getReportSampleDataInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchema/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchema/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchema/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaResponse")
  @ResponseWrapper(localName="getXDOSchemaResponse", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetXDOSchemaResponse")
  @RequestWrapper(localName="getXDOSchema", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetXDOSchema")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getXDOSchemaReturn")
  public byte[] getXDOSchema(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getXDOSchemaInSessionResponse")
  @ResponseWrapper(localName="getXDOSchemaInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetXDOSchemaInSessionResponse")
  @RequestWrapper(localName="getXDOSchemaInSession", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetXDOSchemaInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getXDOSchemaInSessionReturn")
  public byte[] getXDOSchemaInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableLocalesInSessionResponse")
  @ResponseWrapper(localName="getTemplateAvailableLocalesInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableLocalesInSessionResponse")
  @RequestWrapper(localName="getTemplateAvailableLocalesInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableLocalesInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateAvailableLocalesInSessionReturn")
  public List<String> getTemplateAvailableLocalesInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFs/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFs/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFs/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsResponse")
  @ResponseWrapper(localName="getTemplateAvailableXLIFFsResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableXLIFFsResponse")
  @RequestWrapper(localName="getTemplateAvailableXLIFFs", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableXLIFFs")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateAvailableXLIFFsReturn")
  public List<String> getTemplateAvailableXLIFFs(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateAvailableXLIFFsInSessionResponse")
  @ResponseWrapper(localName="getTemplateAvailableXLIFFsInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableXLIFFsInSessionResponse")
  @RequestWrapper(localName="getTemplateAvailableXLIFFsInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateAvailableXLIFFsInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateAvailableXLIFFsInSessionReturn")
  public List<String> getTemplateAvailableXLIFFsInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateInSessionResponse")
  @ResponseWrapper(localName="getTemplateInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateInSessionResponse")
  @RequestWrapper(localName="getTemplateInSession", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetTemplateInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateInSessionReturn")
  public byte[] getTemplateInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getReportParametersInSessionResponse")
  @ResponseWrapper(localName="getReportParametersInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportParametersInSessionResponse")
  @RequestWrapper(localName="getReportParametersInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetReportParametersInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getReportParametersInSessionReturn")
  public com.ceix.ehs.model.ws.proxy.types.ParamNameValues getReportParametersInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRequest")
    com.ceix.ehs.model.ws.proxy.types.ReportRequest reportRequest,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParameters/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParameters/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParameters/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersResponse")
  @ResponseWrapper(localName="getTemplateParametersResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateParametersResponse")
  @RequestWrapper(localName="getTemplateParameters", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetTemplateParameters")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateParametersReturn")
  public List<com.ceix.ehs.model.ws.proxy.types.ParamNameValue> getTemplateParameters(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getTemplateParametersInSessionResponse")
  @ResponseWrapper(localName="getTemplateParametersInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateParametersInSessionResponse")
  @RequestWrapper(localName="getTemplateParametersInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetTemplateParametersInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getTemplateParametersInSessionReturn")
  public List<com.ceix.ehs.model.ws.proxy.types.ParamNameValue> getTemplateParametersInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateID")
    String templateID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectArea/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectArea/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectArea/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaResponse")
  @ResponseWrapper(localName="getListOfSubjectAreaResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetListOfSubjectAreaResponse")
  @RequestWrapper(localName="getListOfSubjectArea", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.GetListOfSubjectArea")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getListOfSubjectAreaReturn")
  public List<String> getListOfSubjectArea(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="connectionName")
    String connectionName)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/getListOfSubjectAreaInSessionResponse")
  @ResponseWrapper(localName="getListOfSubjectAreaInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetListOfSubjectAreaInSessionResponse")
  @RequestWrapper(localName="getListOfSubjectAreaInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.GetListOfSubjectAreaInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="getListOfSubjectAreaInSessionReturn")
  public List<String> getListOfSubjectAreaInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="connectionName")
    String connectionName)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/createReportInSessionResponse")
  @ResponseWrapper(localName="createReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.CreateReportInSessionResponse")
  @RequestWrapper(localName="createReportInSession", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.CreateReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="createReportInSessionReturn")
  public String createReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportName")
    String reportName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="folderAbsolutePathURL")
    String folderAbsolutePathURL, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="dataModelURL")
    String dataModelURL, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateFileName")
    String templateFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="XLIFFFileName")
    String xliffFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="XLIFFData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="updateFlag")
    boolean updateFlag, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinition/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinition/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinition/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateReportDefinitionResponse")
  @ResponseWrapper(localName="updateReportDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateReportDefinitionResponse")
  @RequestWrapper(localName="updateReportDefinition", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UpdateReportDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateReportDefinitionReturn")
  public boolean updateReportDefinition(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsPath")
    String reportAbsPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="newReportDefn")
    com.ceix.ehs.model.ws.proxy.types.ReportDefinition newReportDefn,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCache/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCache/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCache/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeObjectFromCacheResponse")
  @ResponseWrapper(localName="removeObjectFromCacheResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RemoveObjectFromCacheResponse")
  @RequestWrapper(localName="removeObjectFromCache", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RemoveObjectFromCache")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="removeObjectFromCacheReturn")
  public boolean removeObjectFromCache(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="objectPath")
    String objectPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinition/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinition/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinition/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionResponse")
  @ResponseWrapper(localName="updateMobileAppDefinitionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateMobileAppDefinitionResponse")
  @RequestWrapper(localName="updateMobileAppDefinition", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UpdateMobileAppDefinition")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateMobileAppDefinitionReturn")
  public boolean updateMobileAppDefinition(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsPath")
    String reportAbsPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="newMobileAppDefn")
    com.ceix.ehs.model.ws.proxy.types.MobileAppDefinition newMobileAppDefn,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateMobileAppDefinitionInSessionResponse")
  @ResponseWrapper(localName="updateMobileAppDefinitionInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateMobileAppDefinitionInSessionResponse")
  @RequestWrapper(localName="updateMobileAppDefinitionInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateMobileAppDefinitionInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateMobileAppDefinitionInSessionReturn")
  public boolean updateMobileAppDefinitionInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsPath")
    String reportAbsPath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="newMobileAppDefn")
    com.ceix.ehs.model.ws.proxy.types.MobileAppDefinition newMobileAppDefn,
    @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportResponse")
  @ResponseWrapper(localName="uploadTemplateForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadTemplateForReportResponse")
  @RequestWrapper(localName="uploadTemplateForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UploadTemplateForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="uploadTemplateForReportReturn")
  public boolean uploadTemplateForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateName")
    String templateName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateType")
    String templateType, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadTemplateForReportInSessionResponse")
  @ResponseWrapper(localName="uploadTemplateForReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadTemplateForReportInSessionResponse")
  @RequestWrapper(localName="uploadTemplateForReportInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadTemplateForReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="uploadTemplateForReportInSessionReturn")
  public boolean uploadTemplateForReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateName")
    String templateName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateType")
    String templateType, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateTemplateForReportResponse")
  @ResponseWrapper(localName="updateTemplateForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateTemplateForReportResponse")
  @RequestWrapper(localName="updateTemplateForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UpdateTemplateForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateTemplateForReportReturn")
  public boolean updateTemplateForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateName")
    String templateName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateData")
    byte[] templateData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportResponse")
  @ResponseWrapper(localName="removeTemplateForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RemoveTemplateForReportResponse")
  @RequestWrapper(localName="removeTemplateForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.RemoveTemplateForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="removeTemplateForReportReturn")
  public boolean removeTemplateForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateFileName")
    String templateFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/removeTemplateForReportInSessionResponse")
  @ResponseWrapper(localName="removeTemplateForReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RemoveTemplateForReportInSessionResponse")
  @RequestWrapper(localName="removeTemplateForReportInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.RemoveTemplateForReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="removeTemplateForReportInSessionReturn")
  public boolean removeTemplateForReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="templateFileName")
    String templateFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportResponse")
  @ResponseWrapper(localName="uploadXLIFFForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadXLIFFForReportResponse")
  @RequestWrapper(localName="uploadXLIFFForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UploadXLIFFForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="uploadXLIFFForReportReturn")
  public boolean uploadXLIFFForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="xliffData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="layoutFileName")
    String layoutFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportInSessionResponse")
  @ResponseWrapper(localName="updateXLIFFForReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateXLIFFForReportInSessionResponse")
  @RequestWrapper(localName="updateXLIFFForReportInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateXLIFFForReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateXLIFFForReportInSessionReturn")
  public boolean updateXLIFFForReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="xliffData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="layoutFileName")
    String layoutFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReport/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReport/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReport/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/updateXLIFFForReportResponse")
  @ResponseWrapper(localName="updateXLIFFForReportResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UpdateXLIFFForReportResponse")
  @RequestWrapper(localName="updateXLIFFForReport", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UpdateXLIFFForReport")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="updateXLIFFForReportReturn")
  public boolean updateXLIFFForReport(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="xliffData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="layoutFileName")
    String layoutFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportInSession/Fault/InvalidParametersException",
          className=com.ceix.ehs.model.ws.proxy.InvalidParametersException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadXLIFFForReportInSessionResponse")
  @ResponseWrapper(localName="uploadXLIFFForReportInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadXLIFFForReportInSessionResponse")
  @RequestWrapper(localName="uploadXLIFFForReportInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadXLIFFForReportInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="uploadXLIFFForReportInSessionReturn")
  public boolean uploadXLIFFForReportInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportAbsolutePath")
    String reportAbsolutePath, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="xliffData")
    byte[] xliffData, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="layoutFileName")
    String layoutFileName, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="locale")
    String locale, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.InvalidParametersException, com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunkRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunk/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunk/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunkResponse")
  @ResponseWrapper(localName="uploadReportDataChunkResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadReportDataChunkResponse")
  @RequestWrapper(localName="uploadReportDataChunk", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.UploadReportDataChunk")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="uploadReportDataChunkReturn")
  public String uploadReportDataChunk(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="fileID")
    String fileID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportDataChunk")
    byte[] reportDataChunk, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRawDataChunk")
    String reportRawDataChunk, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunkInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunkInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunkInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/uploadReportDataChunkInSessionResponse")
  @ResponseWrapper(localName="uploadReportDataChunkInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadReportDataChunkInSessionResponse")
  @RequestWrapper(localName="uploadReportDataChunkInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.UploadReportDataChunkInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="uploadReportDataChunkInSessionReturn")
  public String uploadReportDataChunkInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="fileID")
    String fileID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportDataChunk")
    byte[] reportDataChunk, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="reportRawDataChunk")
    String reportRawDataChunk, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunkRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunk/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunk/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunkResponse")
  @ResponseWrapper(localName="downloadReportDataChunkResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.DownloadReportDataChunkResponse")
  @RequestWrapper(localName="downloadReportDataChunk", targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    className="com.ceix.ehs.model.ws.proxy.types.DownloadReportDataChunk")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="downloadReportDataChunkReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportDataChunk downloadReportDataChunk(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="fileID")
    String fileID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="beginIdx")
    int beginIdx, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="size")
    int size, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="userID")
    String userID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="password")
    String password)
    throws com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;

  @WebMethod
  @Action(input="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunkInSessionRequest", fault =
      { @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunkInSession/Fault/AccessDeniedException",
          className=com.ceix.ehs.model.ws.proxy.AccessDeniedException.class),
        @FaultAction(value="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunkInSession/Fault/OperationFailedException",
          className=com.ceix.ehs.model.ws.proxy.OperationFailedException.class) },
    output="http://xmlns.oracle.com/oxp/service/v2/ReportService/downloadReportDataChunkInSessionResponse")
  @ResponseWrapper(localName="downloadReportDataChunkInSessionResponse",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.DownloadReportDataChunkInSessionResponse")
  @RequestWrapper(localName="downloadReportDataChunkInSession",
    targetNamespace="http://xmlns.oracle.com/oxp/service/v2", className="com.ceix.ehs.model.ws.proxy.types.DownloadReportDataChunkInSession")
  @WebResult(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
    name="downloadReportDataChunkInSessionReturn")
  public com.ceix.ehs.model.ws.proxy.types.ReportDataChunk downloadReportDataChunkInSession(@WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="fileID")
    String fileID, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="beginIdx")
    int beginIdx, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="size")
    int size, @WebParam(targetNamespace="http://xmlns.oracle.com/oxp/service/v2",
      name="bipSessionToken")
    String bipSessionToken)
    throws com.ceix.ehs.model.ws.proxy.AccessDeniedException, com.ceix.ehs.model.ws.proxy.OperationFailedException;
}
