package com.ceix.delivery.model.views;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 07 11:16:57 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixStsDeliveryLinesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_CEIXSTSDELIVERYLINESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DeliveryLineId {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getDeliveryLineId();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setDeliveryLineId((Number) value);
            }
        }
        ,
        CreationDate {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DeliveryHeaderId {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getDeliveryHeaderId();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setDeliveryHeaderId((Number) value);
            }
        }
        ,
        SalesOrderNumber {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getSalesOrderNumber();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setSalesOrderNumber((String) value);
            }
        }
        ,
        UnitTrainNumber {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getUnitTrainNumber();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setUnitTrainNumber((String) value);
            }
        }
        ,
        ScheduleDate {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getScheduleDate();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setScheduleDate((Date) value);
            }
        }
        ,
        SequenceNum {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getSequenceNum();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setSequenceNum((String) value);
            }
        }
        ,
        CarId {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getCarId();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setCarId((String) value);
            }
        }
        ,
        GrossAllow {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getGrossAllow();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setGrossAllow((String) value);
            }
        }
        ,
        CarTare {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getCarTare();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setCarTare((String) value);
            }
        }
        ,
        Ownership {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getOwnership();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setOwnership((String) value);
            }
        }
        ,
        Weight {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getWeight();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setWeight((String) value);
            }
        }
        ,
        LoadTime {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLoadTime();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setLoadTime((String) value);
            }
        }
        ,
        BinGross {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getBinGross();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setBinGross((String) value);
            }
        }
        ,
        BinTare {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getBinTare();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setBinTare((String) value);
            }
        }
        ,
        LoadedNett {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLoadedNett();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setLoadedNett((String) value);
            }
        }
        ,
        LineChild11 {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLineChild11();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setLineChild11((String) value);
            }
        }
        ,
        ShipmentNumber {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getShipmentNumber();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setShipmentNumber((String) value);
            }
        }
        ,
        Comments {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getComments();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setComments((String) value);
            }
        }
        ,
        FreightCost {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getFreightCost();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setFreightCost((String) value);
            }
        }
        ,
        NewCarId {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getNewCarId();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setNewCarId((String) value);
            }
        }
        ,
        NewTrainNumber {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getNewTrainNumber();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setNewTrainNumber((String) value);
            }
        }
        ,
        WeightInTons {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getWeightInTons();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setWeightInTons((String) value);
            }
        }
        ,
        ProcessedFlag {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getProcessedFlag();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setProcessedFlag((String) value);
            }
        }
        ,
        TransferredFlag {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getTransferredFlag();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setTransferredFlag((String) value);
            }
        }
        ,
        CarPrefix {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getCarPrefix();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setCarPrefix((String) value);
            }
        }
        ,
        Displaycarid {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getDisplaycarid();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setDisplaycarid((String) value);
            }
        }
        ,
        NewCarPrefix {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getNewCarPrefix();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setNewCarPrefix((String) value);
            }
        }
        ,
        RailRoad {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getRailRoad();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setRailRoad((String) value);
            }
        }
        ,
        LoadDate {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLoadDate();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SONUMBER {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getSONUMBER();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setSONUMBER((String) value);
            }
        }
        ,
        ItemNumber {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getItemNumber();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setItemNumber((String) value);
            }
        }
        ,
        Straggler {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getStraggler();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setStraggler((String) value);
            }
        }
        ,
        LoadOrigin {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getLoadOrigin();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setLoadOrigin((String) value);
            }
        }
        ,
        Destination {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getDestination();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setDestination((String) value);
            }
        }
        ,
        Freight {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getFreight();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setFreight((String) value);
            }
        }
        ,
        CpWaybillFlag {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getCpWaybillFlag();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setCpWaybillFlag((String) value);
            }
        }
        ,
        Surcharge {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getSurcharge();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setSurcharge((String) value);
            }
        }
        ,
        SelectFLag {
            protected Object get(CeixStsDeliveryLinesVORowImpl obj) {
                return obj.getSelectFLag();
            }

            protected void put(CeixStsDeliveryLinesVORowImpl obj, Object value) {
                obj.setSelectFLag((Boolean) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;


        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(CeixStsDeliveryLinesVORowImpl object);

        protected abstract void put(CeixStsDeliveryLinesVORowImpl object, Object value);
    }


    public static final int DELIVERYLINEID = AttributesEnum.DeliveryLineId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int DELIVERYHEADERID = AttributesEnum.DeliveryHeaderId.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int UNITTRAINNUMBER = AttributesEnum.UnitTrainNumber.index();
    public static final int SCHEDULEDATE = AttributesEnum.ScheduleDate.index();
    public static final int SEQUENCENUM = AttributesEnum.SequenceNum.index();
    public static final int CARID = AttributesEnum.CarId.index();
    public static final int GROSSALLOW = AttributesEnum.GrossAllow.index();
    public static final int CARTARE = AttributesEnum.CarTare.index();
    public static final int OWNERSHIP = AttributesEnum.Ownership.index();
    public static final int WEIGHT = AttributesEnum.Weight.index();
    public static final int LOADTIME = AttributesEnum.LoadTime.index();
    public static final int BINGROSS = AttributesEnum.BinGross.index();
    public static final int BINTARE = AttributesEnum.BinTare.index();
    public static final int LOADEDNETT = AttributesEnum.LoadedNett.index();
    public static final int LINECHILD11 = AttributesEnum.LineChild11.index();
    public static final int SHIPMENTNUMBER = AttributesEnum.ShipmentNumber.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int FREIGHTCOST = AttributesEnum.FreightCost.index();
    public static final int NEWCARID = AttributesEnum.NewCarId.index();
    public static final int NEWTRAINNUMBER = AttributesEnum.NewTrainNumber.index();
    public static final int WEIGHTINTONS = AttributesEnum.WeightInTons.index();
    public static final int PROCESSEDFLAG = AttributesEnum.ProcessedFlag.index();
    public static final int TRANSFERREDFLAG = AttributesEnum.TransferredFlag.index();
    public static final int CARPREFIX = AttributesEnum.CarPrefix.index();
    public static final int DISPLAYCARID = AttributesEnum.Displaycarid.index();
    public static final int NEWCARPREFIX = AttributesEnum.NewCarPrefix.index();
    public static final int RAILROAD = AttributesEnum.RailRoad.index();
    public static final int LOADDATE = AttributesEnum.LoadDate.index();
    public static final int SONUMBER = AttributesEnum.SONUMBER.index();
    public static final int ITEMNUMBER = AttributesEnum.ItemNumber.index();
    public static final int STRAGGLER = AttributesEnum.Straggler.index();
    public static final int LOADORIGIN = AttributesEnum.LoadOrigin.index();
    public static final int DESTINATION = AttributesEnum.Destination.index();
    public static final int FREIGHT = AttributesEnum.Freight.index();
    public static final int CPWAYBILLFLAG = AttributesEnum.CpWaybillFlag.index();
    public static final int SURCHARGE = AttributesEnum.Surcharge.index();
    public static final int SELECTFLAG = AttributesEnum.SelectFLag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CeixStsDeliveryLinesVORowImpl() {
    }

    /**
     * Gets CeixStsDeliveryLinesEO entity object.
     * @return the CeixStsDeliveryLinesEO
     */
    public EntityImpl getCeixStsDeliveryLinesEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DELIVERY_LINE_ID using the alias name DeliveryLineId.
     * @return the DELIVERY_LINE_ID
     */
    public Number getDeliveryLineId() {
        return (Number) getAttributeInternal(DELIVERYLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_LINE_ID using the alias name DeliveryLineId.
     * @param value value to set the DELIVERY_LINE_ID
     */
    public void setDeliveryLineId(Number value) {
        setAttributeInternal(DELIVERYLINEID, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for DELIVERY_HEADER_ID using the alias name DeliveryHeaderId.
     * @return the DELIVERY_HEADER_ID
     */
    public Number getDeliveryHeaderId() {
        return (Number) getAttributeInternal(DELIVERYHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_HEADER_ID using the alias name DeliveryHeaderId.
     * @param value value to set the DELIVERY_HEADER_ID
     */
    public void setDeliveryHeaderId(Number value) {
        setAttributeInternal(DELIVERYHEADERID, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @return the SALES_ORDER_NUMBER
     */
    public String getSalesOrderNumber() {
        return (String) getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @param value value to set the SALES_ORDER_NUMBER
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for UNIT_TRAIN_NUMBER using the alias name UnitTrainNumber.
     * @return the UNIT_TRAIN_NUMBER
     */
    public String getUnitTrainNumber() {
        return (String) getAttributeInternal(UNITTRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_TRAIN_NUMBER using the alias name UnitTrainNumber.
     * @param value value to set the UNIT_TRAIN_NUMBER
     */
    public void setUnitTrainNumber(String value) {
        setAttributeInternal(UNITTRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for SCHEDULE_DATE using the alias name ScheduleDate.
     * @return the SCHEDULE_DATE
     */
    public Date getScheduleDate() {
        return (Date) getAttributeInternal(SCHEDULEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEDULE_DATE using the alias name ScheduleDate.
     * @param value value to set the SCHEDULE_DATE
     */
    public void setScheduleDate(Date value) {
        setAttributeInternal(SCHEDULEDATE, value);
    }

    /**
     * Gets the attribute value for SEQUENCE_NUM using the alias name SequenceNum.
     * @return the SEQUENCE_NUM
     */
    public String getSequenceNum() {
        return (String) getAttributeInternal(SEQUENCENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for SEQUENCE_NUM using the alias name SequenceNum.
     * @param value value to set the SEQUENCE_NUM
     */
    public void setSequenceNum(String value) {
        setAttributeInternal(SEQUENCENUM, value);
    }

    /**
     * Gets the attribute value for CAR_ID using the alias name CarId.
     * @return the CAR_ID
     */
    public String getCarId() {
        return (String) getAttributeInternal(CARID);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_ID using the alias name CarId.
     * @param value value to set the CAR_ID
     */
    public void setCarId(String value) {
        setAttributeInternal(CARID, value);
    }

    /**
     * Gets the attribute value for GROSS_ALLOW using the alias name GrossAllow.
     * @return the GROSS_ALLOW
     */
    public String getGrossAllow() {
        return (String) getAttributeInternal(GROSSALLOW);
    }

    /**
     * Sets <code>value</code> as attribute value for GROSS_ALLOW using the alias name GrossAllow.
     * @param value value to set the GROSS_ALLOW
     */
    public void setGrossAllow(String value) {
        setAttributeInternal(GROSSALLOW, value);
    }

    /**
     * Gets the attribute value for CAR_TARE using the alias name CarTare.
     * @return the CAR_TARE
     */
    public String getCarTare() {
        return (String) getAttributeInternal(CARTARE);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_TARE using the alias name CarTare.
     * @param value value to set the CAR_TARE
     */
    public void setCarTare(String value) {
        setAttributeInternal(CARTARE, value);
    }

    /**
     * Gets the attribute value for OWNERSHIP using the alias name Ownership.
     * @return the OWNERSHIP
     */
    public String getOwnership() {
        return (String) getAttributeInternal(OWNERSHIP);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNERSHIP using the alias name Ownership.
     * @param value value to set the OWNERSHIP
     */
    public void setOwnership(String value) {
        setAttributeInternal(OWNERSHIP, value);
    }

    /**
     * Gets the attribute value for WEIGHT using the alias name Weight.
     * @return the WEIGHT
     */
    public String getWeight() {
        return (String) getAttributeInternal(WEIGHT);
    }

    /**
     * Sets <code>value</code> as attribute value for WEIGHT using the alias name Weight.
     * @param value value to set the WEIGHT
     */
    public void setWeight(String value) {
        setAttributeInternal(WEIGHT, value);
    }

    /**
     * Gets the attribute value for LOAD_TIME using the alias name LoadTime.
     * @return the LOAD_TIME
     */
    public String getLoadTime() {
        return (String) getAttributeInternal(LOADTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAD_TIME using the alias name LoadTime.
     * @param value value to set the LOAD_TIME
     */
    public void setLoadTime(String value) {
        setAttributeInternal(LOADTIME, value);
    }

    /**
     * Gets the attribute value for BIN_GROSS using the alias name BinGross.
     * @return the BIN_GROSS
     */
    public String getBinGross() {
        return (String) getAttributeInternal(BINGROSS);
    }

    /**
     * Sets <code>value</code> as attribute value for BIN_GROSS using the alias name BinGross.
     * @param value value to set the BIN_GROSS
     */
    public void setBinGross(String value) {
        setAttributeInternal(BINGROSS, value);
    }

    /**
     * Gets the attribute value for BIN_TARE using the alias name BinTare.
     * @return the BIN_TARE
     */
    public String getBinTare() {
        return (String) getAttributeInternal(BINTARE);
    }

    /**
     * Sets <code>value</code> as attribute value for BIN_TARE using the alias name BinTare.
     * @param value value to set the BIN_TARE
     */
    public void setBinTare(String value) {
        setAttributeInternal(BINTARE, value);
    }

    /**
     * Gets the attribute value for LOADED_NETT using the alias name LoadedNett.
     * @return the LOADED_NETT
     */
    public String getLoadedNett() {
        return (String) getAttributeInternal(LOADEDNETT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOADED_NETT using the alias name LoadedNett.
     * @param value value to set the LOADED_NETT
     */
    public void setLoadedNett(String value) {
        setAttributeInternal(LOADEDNETT, value);
    }

    /**
     * Gets the attribute value for LINE_CHILD_11 using the alias name LineChild11.
     * @return the LINE_CHILD_11
     */
    public String getLineChild11() {
        return (String) getAttributeInternal(LINECHILD11);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_CHILD_11 using the alias name LineChild11.
     * @param value value to set the LINE_CHILD_11
     */
    public void setLineChild11(String value) {
        setAttributeInternal(LINECHILD11, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber.
     * @return the SHIPMENT_NUMBER
     */
    public String getShipmentNumber() {
        return (String) getAttributeInternal(SHIPMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber.
     * @param value value to set the SHIPMENT_NUMBER
     */
    public void setShipmentNumber(String value) {
        setAttributeInternal(SHIPMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectFLag.
     * @return the SelectFLag
     */
    public Boolean getSelectFLag() {
        return (Boolean) getAttributeInternal(SELECTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectFLag.
     * @param value value to set the  SelectFLag
     */
    public void setSelectFLag(Boolean value) {
        setAttributeInternal(SELECTFLAG, value);
    }


    /**
     * Gets the attribute value for FREIGHT using the alias name Freight.
     * @return the FREIGHT
     */
    public String getFreight() {
        return (String) getAttributeInternal(FREIGHT);
    }

    /**
     * Sets <code>value</code> as attribute value for FREIGHT using the alias name Freight.
     * @param value value to set the FREIGHT
     */
    public void setFreight(String value) {
        setAttributeInternal(FREIGHT, value);
    }


    /**
     * Gets the attribute value for CP_WAYBILL_FLAG using the alias name CpWaybillFlag.
     * @return the CP_WAYBILL_FLAG
     */
    public String getCpWaybillFlag() {
        return (String) getAttributeInternal(CPWAYBILLFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CP_WAYBILL_FLAG using the alias name CpWaybillFlag.
     * @param value value to set the CP_WAYBILL_FLAG
     */
    public void setCpWaybillFlag(String value) {
        setAttributeInternal(CPWAYBILLFLAG, value);
    }

    /**
     * Gets the attribute value for STRAGGLER using the alias name Straggler.
     * @return the STRAGGLER
     */
    public String getStraggler() {
        return (String) getAttributeInternal(STRAGGLER);
    }

    /**
     * Sets <code>value</code> as attribute value for STRAGGLER using the alias name Straggler.
     * @param value value to set the STRAGGLER
     */
    public void setStraggler(String value) {
        setAttributeInternal(STRAGGLER, value);
    }

    /**
     * Gets the attribute value for DESTINATION using the alias name Destination.
     * @return the DESTINATION
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION using the alias name Destination.
     * @param value value to set the DESTINATION
     */
    public void setDestination(String value) {
        setAttributeInternal(DESTINATION, value);
    }
    
    /**
     * Gets the attribute value for SURCHARGE using the alias name Surcharge.
     * @return the SURCHARGE
     */
    public String getSurcharge() {
        return (String) getAttributeInternal(SURCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for SURCHARGE using the alias name Surcharge.
     * @param value value to set the SURCHARGE
     */
    public void setSurcharge(String value) {
        setAttributeInternal(SURCHARGE, value);
    }

    /**
     * Gets the attribute value for LOAD_ORIGIN using the alias name LoadOrigin.
     * @return the LOAD_ORIGIN
     */
    public String getLoadOrigin() {
        return (String) getAttributeInternal(LOADORIGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAD_ORIGIN using the alias name LoadOrigin.
     * @param value value to set the LOAD_ORIGIN
     */
    public void setLoadOrigin(String value) {
        setAttributeInternal(LOADORIGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getItemNumber() {
        return (String) getAttributeInternal(ITEMNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setItemNumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for FREIGHT_COST using the alias name FreightCost.
     * @return the FREIGHT_COST
     */
    public String getFreightCost() {
        return (String) getAttributeInternal(FREIGHTCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for FREIGHT_COST using the alias name FreightCost.
     * @param value value to set the FREIGHT_COST
     */
    public void setFreightCost(String value) {
        setAttributeInternal(FREIGHTCOST, value);
    }

    /**
     * Gets the attribute value for NEW_CAR_ID using the alias name NewCarId.
     * @return the NEW_CAR_ID
     */
    public String getNewCarId() {
        return (String) getAttributeInternal(NEWCARID);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_CAR_ID using the alias name NewCarId.
     * @param value value to set the NEW_CAR_ID
     */
    public void setNewCarId(String value) {
        setAttributeInternal(NEWCARID, value);
    }

    /**
     * Gets the attribute value for NEW_TRAIN_NUMBER using the alias name NewTrainNumber.
     * @return the NEW_TRAIN_NUMBER
     */
    public String getNewTrainNumber() {
        return (String) getAttributeInternal(NEWTRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_TRAIN_NUMBER using the alias name NewTrainNumber.
     * @param value value to set the NEW_TRAIN_NUMBER
     */
    public void setNewTrainNumber(String value) {
        setAttributeInternal(NEWTRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for WEIGHT_IN_TONS using the alias name WeightInTons.
     * @return the WEIGHT_IN_TONS
     */
    public String getWeightInTons() {
        return (String) getAttributeInternal(WEIGHTINTONS);
    }

    /**
     * Sets <code>value</code> as attribute value for WEIGHT_IN_TONS using the alias name WeightInTons.
     * @param value value to set the WEIGHT_IN_TONS
     */
    public void setWeightInTons(String value) {
        setAttributeInternal(WEIGHTINTONS, value);
    }

    /**
     * Gets the attribute value for PROCESSED_FLAG using the alias name ProcessedFlag.
     * @return the PROCESSED_FLAG
     */
    public String getProcessedFlag() {
        return (String) getAttributeInternal(PROCESSEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESSED_FLAG using the alias name ProcessedFlag.
     * @param value value to set the PROCESSED_FLAG
     */
    public void setProcessedFlag(String value) {
        setAttributeInternal(PROCESSEDFLAG, value);
    }

    /**
     * Gets the attribute value for TRANSFERRED_FLAG using the alias name TransferredFlag.
     * @return the TRANSFERRED_FLAG
     */
    public String getTransferredFlag() {
        return (String) getAttributeInternal(TRANSFERREDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFERRED_FLAG using the alias name TransferredFlag.
     * @param value value to set the TRANSFERRED_FLAG
     */
    public void setTransferredFlag(String value) {
        setAttributeInternal(TRANSFERREDFLAG, value);
    }

    /**
     * Gets the attribute value for CAR_PREFIX using the alias name CarPrefix.
     * @return the CAR_PREFIX
     */
    public String getCarPrefix() {
        return (String) getAttributeInternal(CARPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_PREFIX using the alias name CarPrefix.
     * @param value value to set the CAR_PREFIX
     */
    public void setCarPrefix(String value) {
        setAttributeInternal(CARPREFIX, value);
    }

    /**
     * Gets the attribute value for DISPLAYCARID using the alias name Displaycarid.
     * @return the DISPLAYCARID
     */
    public String getDisplaycarid() {
        return (String) getAttributeInternal(DISPLAYCARID);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPLAYCARID using the alias name Displaycarid.
     * @param value value to set the DISPLAYCARID
     */
    public void setDisplaycarid(String value) {
        setAttributeInternal(DISPLAYCARID, value);
    }

    /**
     * Gets the attribute value for NEW_CAR_PREFIX using the alias name NewCarPrefix.
     * @return the NEW_CAR_PREFIX
     */
    public String getNewCarPrefix() {
        return (String) getAttributeInternal(NEWCARPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_CAR_PREFIX using the alias name NewCarPrefix.
     * @param value value to set the NEW_CAR_PREFIX
     */
    public void setNewCarPrefix(String value) {
        setAttributeInternal(NEWCARPREFIX, value);
    }

    /**
     * Gets the attribute value for RAIL_ROAD using the alias name RailRoad.
     * @return the RAIL_ROAD
     */
    public String getRailRoad() {
        return (String) getAttributeInternal(RAILROAD);
    }

    /**
     * Sets <code>value</code> as attribute value for RAIL_ROAD using the alias name RailRoad.
     * @param value value to set the RAIL_ROAD
     */
    public void setRailRoad(String value) {
        setAttributeInternal(RAILROAD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LoadDate.
     * @return the LoadDate
     */
    public Date getLoadDate() {
        return (Date) getAttributeInternal(LOADDATE);
    }


    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1_1.
     * @return the ATTRIBUTE1
     */
    public String getSONUMBER() {
        return (String) getAttributeInternal(SONUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1_1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setSONUMBER(String value) {
        setAttributeInternal(SONUMBER, value);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
