package com.ceix.ehs.model.entities;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 10 19:10:29 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixEhsClinicalLogEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public CeixEhsClinicalLogEOCollImpl() {
    }
}
