package com.ceix.ehs.model.entities;

import java.sql.PreparedStatement;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import java.sql.ResultSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 10 11:29:21 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixEhsViolationNoticeEOImpl extends EntityImpl {
    /**
     * Validation method for CitationOrdNum.
     */
    public boolean validateCitationOrdNum(String citationordnum) {

        String sql =
            "select * from CEIX_EHS_VIOLATION_NOTICE where CITATION_ORD_NUM = '"+citationordnum+"'";
        PreparedStatement createprep;
        ResultSet rs;
        try {
            System.out.println(sql);
            createprep = getDBTransaction().createPreparedStatement(sql, 1);
            rs = createprep.executeQuery();
            if (rs.next()) {
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ViolationId {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getViolationId();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setViolationId((Number)value);
            }
        }
        ,
        MineId {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getMineId();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setMineId((String)value);
            }
        }
        ,
        VioJurisdiction {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getVioJurisdiction();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setVioJurisdiction((String)value);
            }
        }
        ,
        CitationOrdNum {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getCitationOrdNum();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setCitationOrdNum((String)value);
            }
        }
        ,
        CitationDate {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getCitationDate();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setCitationDate((Date)value);
            }
        }
        ,
        InspectionType {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getInspectionType();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setInspectionType((String)value);
            }
        }
        ,
        ViolationState {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getViolationState();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setViolationState((String)value);
            }
        }
        ,
        InspectorState {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getInspectorState();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setInspectorState((String)value);
            }
        }
        ,
        InspectorFederal {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getInspectorFederal();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setInspectorFederal((String)value);
            }
        }
        ,
        ConsolEscort {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getConsolEscort();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setConsolEscort((String)value);
            }
        }
        ,
        ShiftForeman {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getShiftForeman();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setShiftForeman((String)value);
            }
        }
        ,
        Abated {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAbated();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAbated((String)value);
            }
        }
        ,
        Vacated {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getVacated();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setVacated((String)value);
            }
        }
        ,
        ViolationFedCode {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getViolationFedCode();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setViolationFedCode((String)value);
            }
        }
        ,
        ViolationFedPart {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getViolationFedPart();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setViolationFedPart((String)value);
            }
        }
        ,
        CombMaterial {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getCombMaterial();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setCombMaterial((String)value);
            }
        }
        ,
        InjuryLikely {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getInjuryLikely();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setInjuryLikely((String)value);
            }
        }
        ,
        InjuryImpact {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getInjuryImpact();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setInjuryImpact((String)value);
            }
        }
        ,
        SigSub {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getSigSub();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setSigSub((String)value);
            }
        }
        ,
        PersonsEffected {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getPersonsEffected();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setPersonsEffected((String)value);
            }
        }
        ,
        Negligence {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getNegligence();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setNegligence((String)value);
            }
        }
        ,
        ActionType {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getActionType();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setActionType((String)value);
            }
        }
        ,
        IssuanceType {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getIssuanceType();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setIssuanceType((String)value);
            }
        }
        ,
        MineArea {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getMineArea();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setMineArea((String)value);
            }
        }
        ,
        MineLocation {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getMineLocation();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setMineLocation((String)value);
            }
        }
        ,
        ChargeArea {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getChargeArea();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setChargeArea((String)value);
            }
        }
        ,
        VioDescription {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getVioDescription();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setVioDescription((String)value);
            }
        }
        ,
        Comments {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getComments();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        ConfRequested {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getConfRequested();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setConfRequested((String)value);
            }
        }
        ,
        ProposedPenalty {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getProposedPenalty();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setProposedPenalty((Number)value);
            }
        }
        ,
        CaseNumber {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getCaseNumber();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setCaseNumber((String)value);
            }
        }
        ,
        SubmittedDate {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getSubmittedDate();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setSubmittedDate((Date)value);
            }
        }
        ,
        DocketNumber {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getDocketNumber();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setDocketNumber((String)value);
            }
        }
        ,
        DocketDate {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getDocketDate();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setDocketDate((Date)value);
            }
        }
        ,
        HearingResult {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getHearingResult();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setHearingResult((String)value);
            }
        }
        ,
        SettlementAmt {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getSettlementAmt();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setSettlementAmt((Number)value);
            }
        }
        ,
        Notes {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getNotes();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setNotes((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Stic {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getStic();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setStic((String)value);
            }
        }
        ,
        Plant {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getPlant();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setPlant((String)value);
            }
        }
        ,
        Outby {
            public Object get(CeixEhsViolationNoticeEOImpl obj) {
                return obj.getOutby();
            }

            public void put(CeixEhsViolationNoticeEOImpl obj, Object value) {
                obj.setOutby((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CeixEhsViolationNoticeEOImpl object);

        public abstract void put(CeixEhsViolationNoticeEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int VIOLATIONID = AttributesEnum.ViolationId.index();
    public static final int MINEID = AttributesEnum.MineId.index();
    public static final int VIOJURISDICTION = AttributesEnum.VioJurisdiction.index();
    public static final int CITATIONORDNUM = AttributesEnum.CitationOrdNum.index();
    public static final int CITATIONDATE = AttributesEnum.CitationDate.index();
    public static final int INSPECTIONTYPE = AttributesEnum.InspectionType.index();
    public static final int VIOLATIONSTATE = AttributesEnum.ViolationState.index();
    public static final int INSPECTORSTATE = AttributesEnum.InspectorState.index();
    public static final int INSPECTORFEDERAL = AttributesEnum.InspectorFederal.index();
    public static final int CONSOLESCORT = AttributesEnum.ConsolEscort.index();
    public static final int SHIFTFOREMAN = AttributesEnum.ShiftForeman.index();
    public static final int ABATED = AttributesEnum.Abated.index();
    public static final int VACATED = AttributesEnum.Vacated.index();
    public static final int VIOLATIONFEDCODE = AttributesEnum.ViolationFedCode.index();
    public static final int VIOLATIONFEDPART = AttributesEnum.ViolationFedPart.index();
    public static final int COMBMATERIAL = AttributesEnum.CombMaterial.index();
    public static final int INJURYLIKELY = AttributesEnum.InjuryLikely.index();
    public static final int INJURYIMPACT = AttributesEnum.InjuryImpact.index();
    public static final int SIGSUB = AttributesEnum.SigSub.index();
    public static final int PERSONSEFFECTED = AttributesEnum.PersonsEffected.index();
    public static final int NEGLIGENCE = AttributesEnum.Negligence.index();
    public static final int ACTIONTYPE = AttributesEnum.ActionType.index();
    public static final int ISSUANCETYPE = AttributesEnum.IssuanceType.index();
    public static final int MINEAREA = AttributesEnum.MineArea.index();
    public static final int MINELOCATION = AttributesEnum.MineLocation.index();
    public static final int CHARGEAREA = AttributesEnum.ChargeArea.index();
    public static final int VIODESCRIPTION = AttributesEnum.VioDescription.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CONFREQUESTED = AttributesEnum.ConfRequested.index();
    public static final int PROPOSEDPENALTY = AttributesEnum.ProposedPenalty.index();
    public static final int CASENUMBER = AttributesEnum.CaseNumber.index();
    public static final int SUBMITTEDDATE = AttributesEnum.SubmittedDate.index();
    public static final int DOCKETNUMBER = AttributesEnum.DocketNumber.index();
    public static final int DOCKETDATE = AttributesEnum.DocketDate.index();
    public static final int HEARINGRESULT = AttributesEnum.HearingResult.index();
    public static final int SETTLEMENTAMT = AttributesEnum.SettlementAmt.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int STIC = AttributesEnum.Stic.index();
    public static final int PLANT = AttributesEnum.Plant.index();
    public static final int OUTBY = AttributesEnum.Outby.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CeixEhsViolationNoticeEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.ceix.ehs.model.entities.CeixEhsViolationNoticeEO");
    }

    /**
     * Gets the attribute value for ViolationId, using the alias name ViolationId.
     * @return the ViolationId
     */
    public Number getViolationId() {
        return (Number)getAttributeInternal(VIOLATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ViolationId.
     * @param value value to set the ViolationId
     */
    public void setViolationId(Number value) {
        setAttributeInternal(VIOLATIONID, value);
    }

    /**
     * Gets the attribute value for MineId, using the alias name MineId.
     * @return the MineId
     */
    public String getMineId() {
        return (String)getAttributeInternal(MINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MineId.
     * @param value value to set the MineId
     */
    public void setMineId(String value) {
        setAttributeInternal(MINEID, value);
    }

    /**
     * Gets the attribute value for VioJurisdiction, using the alias name VioJurisdiction.
     * @return the VioJurisdiction
     */
    public String getVioJurisdiction() {
        return (String)getAttributeInternal(VIOJURISDICTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for VioJurisdiction.
     * @param value value to set the VioJurisdiction
     */
    public void setVioJurisdiction(String value) {
        setAttributeInternal(VIOJURISDICTION, value);
    }

    /**
     * Gets the attribute value for CitationOrdNum, using the alias name CitationOrdNum.
     * @return the CitationOrdNum
     */
    public String getCitationOrdNum() {
        return (String)getAttributeInternal(CITATIONORDNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for CitationOrdNum.
     * @param value value to set the CitationOrdNum
     */
    public void setCitationOrdNum(String value) {
        setAttributeInternal(CITATIONORDNUM, value);
    }

    /**
     * Gets the attribute value for CitationDate, using the alias name CitationDate.
     * @return the CitationDate
     */
    public Date getCitationDate() {
        return (Date)getAttributeInternal(CITATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CitationDate.
     * @param value value to set the CitationDate
     */
    public void setCitationDate(Date value) {
        setAttributeInternal(CITATIONDATE, value);
    }

    /**
     * Gets the attribute value for InspectionType, using the alias name InspectionType.
     * @return the InspectionType
     */
    public String getInspectionType() {
        return (String)getAttributeInternal(INSPECTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectionType.
     * @param value value to set the InspectionType
     */
    public void setInspectionType(String value) {
        setAttributeInternal(INSPECTIONTYPE, value);
    }

    /**
     * Gets the attribute value for ViolationState, using the alias name ViolationState.
     * @return the ViolationState
     */
    public String getViolationState() {
        return (String)getAttributeInternal(VIOLATIONSTATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ViolationState.
     * @param value value to set the ViolationState
     */
    public void setViolationState(String value) {
        setAttributeInternal(VIOLATIONSTATE, value);
    }

    /**
     * Gets the attribute value for InspectorState, using the alias name InspectorState.
     * @return the InspectorState
     */
    public String getInspectorState() {
        return (String)getAttributeInternal(INSPECTORSTATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectorState.
     * @param value value to set the InspectorState
     */
    public void setInspectorState(String value) {
        setAttributeInternal(INSPECTORSTATE, value);
    }

    /**
     * Gets the attribute value for InspectorFederal, using the alias name InspectorFederal.
     * @return the InspectorFederal
     */
    public String getInspectorFederal() {
        return (String)getAttributeInternal(INSPECTORFEDERAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectorFederal.
     * @param value value to set the InspectorFederal
     */
    public void setInspectorFederal(String value) {
        setAttributeInternal(INSPECTORFEDERAL, value);
    }

    /**
     * Gets the attribute value for ConsolEscort, using the alias name ConsolEscort.
     * @return the ConsolEscort
     */
    public String getConsolEscort() {
        return (String)getAttributeInternal(CONSOLESCORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConsolEscort.
     * @param value value to set the ConsolEscort
     */
    public void setConsolEscort(String value) {
        setAttributeInternal(CONSOLESCORT, value);
    }

    /**
     * Gets the attribute value for ShiftForeman, using the alias name ShiftForeman.
     * @return the ShiftForeman
     */
    public String getShiftForeman() {
        return (String)getAttributeInternal(SHIFTFOREMAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShiftForeman.
     * @param value value to set the ShiftForeman
     */
    public void setShiftForeman(String value) {
        setAttributeInternal(SHIFTFOREMAN, value);
    }

    /**
     * Gets the attribute value for Abated, using the alias name Abated.
     * @return the Abated
     */
    public String getAbated() {
        return (String)getAttributeInternal(ABATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Abated.
     * @param value value to set the Abated
     */
    public void setAbated(String value) {
        setAttributeInternal(ABATED, value);
    }

    /**
     * Gets the attribute value for Vacated, using the alias name Vacated.
     * @return the Vacated
     */
    public String getVacated() {
        return (String)getAttributeInternal(VACATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Vacated.
     * @param value value to set the Vacated
     */
    public void setVacated(String value) {
        setAttributeInternal(VACATED, value);
    }

    /**
     * Gets the attribute value for ViolationFedCode, using the alias name ViolationFedCode.
     * @return the ViolationFedCode
     */
    public String getViolationFedCode() {
        return (String)getAttributeInternal(VIOLATIONFEDCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ViolationFedCode.
     * @param value value to set the ViolationFedCode
     */
    public void setViolationFedCode(String value) {
        setAttributeInternal(VIOLATIONFEDCODE, value);
    }

    /**
     * Gets the attribute value for ViolationFedPart, using the alias name ViolationFedPart.
     * @return the ViolationFedPart
     */
    public String getViolationFedPart() {
        return (String)getAttributeInternal(VIOLATIONFEDPART);
    }

    /**
     * Sets <code>value</code> as the attribute value for ViolationFedPart.
     * @param value value to set the ViolationFedPart
     */
    public void setViolationFedPart(String value) {
        setAttributeInternal(VIOLATIONFEDPART, value);
    }

    /**
     * Gets the attribute value for CombMaterial, using the alias name CombMaterial.
     * @return the CombMaterial
     */
    public String getCombMaterial() {
        return (String)getAttributeInternal(COMBMATERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CombMaterial.
     * @param value value to set the CombMaterial
     */
    public void setCombMaterial(String value) {
        setAttributeInternal(COMBMATERIAL, value);
    }

    /**
     * Gets the attribute value for InjuryLikely, using the alias name InjuryLikely.
     * @return the InjuryLikely
     */
    public String getInjuryLikely() {
        return (String)getAttributeInternal(INJURYLIKELY);
    }

    /**
     * Sets <code>value</code> as the attribute value for InjuryLikely.
     * @param value value to set the InjuryLikely
     */
    public void setInjuryLikely(String value) {
        setAttributeInternal(INJURYLIKELY, value);
    }

    /**
     * Gets the attribute value for InjuryImpact, using the alias name InjuryImpact.
     * @return the InjuryImpact
     */
    public String getInjuryImpact() {
        return (String)getAttributeInternal(INJURYIMPACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InjuryImpact.
     * @param value value to set the InjuryImpact
     */
    public void setInjuryImpact(String value) {
        setAttributeInternal(INJURYIMPACT, value);
    }

    /**
     * Gets the attribute value for SigSub, using the alias name SigSub.
     * @return the SigSub
     */
    public String getSigSub() {
        return (String)getAttributeInternal(SIGSUB);
    }

    /**
     * Sets <code>value</code> as the attribute value for SigSub.
     * @param value value to set the SigSub
     */
    public void setSigSub(String value) {
        setAttributeInternal(SIGSUB, value);
    }

    /**
     * Gets the attribute value for PersonsEffected, using the alias name PersonsEffected.
     * @return the PersonsEffected
     */
    public String getPersonsEffected() {
        return (String)getAttributeInternal(PERSONSEFFECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonsEffected.
     * @param value value to set the PersonsEffected
     */
    public void setPersonsEffected(String value) {
        setAttributeInternal(PERSONSEFFECTED, value);
    }

    /**
     * Gets the attribute value for Negligence, using the alias name Negligence.
     * @return the Negligence
     */
    public String getNegligence() {
        return (String)getAttributeInternal(NEGLIGENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Negligence.
     * @param value value to set the Negligence
     */
    public void setNegligence(String value) {
        setAttributeInternal(NEGLIGENCE, value);
    }

    /**
     * Gets the attribute value for ActionType, using the alias name ActionType.
     * @return the ActionType
     */
    public String getActionType() {
        return (String)getAttributeInternal(ACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActionType.
     * @param value value to set the ActionType
     */
    public void setActionType(String value) {
        setAttributeInternal(ACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for IssuanceType, using the alias name IssuanceType.
     * @return the IssuanceType
     */
    public String getIssuanceType() {
        return (String)getAttributeInternal(ISSUANCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssuanceType.
     * @param value value to set the IssuanceType
     */
    public void setIssuanceType(String value) {
        setAttributeInternal(ISSUANCETYPE, value);
    }

    /**
     * Gets the attribute value for MineArea, using the alias name MineArea.
     * @return the MineArea
     */
    public String getMineArea() {
        return (String)getAttributeInternal(MINEAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for MineArea.
     * @param value value to set the MineArea
     */
    public void setMineArea(String value) {
        setAttributeInternal(MINEAREA, value);
    }

    /**
     * Gets the attribute value for MineLocation, using the alias name MineLocation.
     * @return the MineLocation
     */
    public String getMineLocation() {
        return (String)getAttributeInternal(MINELOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for MineLocation.
     * @param value value to set the MineLocation
     */
    public void setMineLocation(String value) {
        setAttributeInternal(MINELOCATION, value);
    }

    /**
     * Gets the attribute value for ChargeArea, using the alias name ChargeArea.
     * @return the ChargeArea
     */
    public String getChargeArea() {
        return (String)getAttributeInternal(CHARGEAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChargeArea.
     * @param value value to set the ChargeArea
     */
    public void setChargeArea(String value) {
        setAttributeInternal(CHARGEAREA, value);
    }

    /**
     * Gets the attribute value for VioDescription, using the alias name VioDescription.
     * @return the VioDescription
     */
    public String getVioDescription() {
        return (String)getAttributeInternal(VIODESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for VioDescription.
     * @param value value to set the VioDescription
     */
    public void setVioDescription(String value) {
        setAttributeInternal(VIODESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ConfRequested, using the alias name ConfRequested.
     * @return the ConfRequested
     */
    public String getConfRequested() {
        return (String)getAttributeInternal(CONFREQUESTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConfRequested.
     * @param value value to set the ConfRequested
     */
    public void setConfRequested(String value) {
        setAttributeInternal(CONFREQUESTED, value);
    }

    /**
     * Gets the attribute value for ProposedPenalty, using the alias name ProposedPenalty.
     * @return the ProposedPenalty
     */
    public Number getProposedPenalty() {
        return (Number)getAttributeInternal(PROPOSEDPENALTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProposedPenalty.
     * @param value value to set the ProposedPenalty
     */
    public void setProposedPenalty(Number value) {
        setAttributeInternal(PROPOSEDPENALTY, value);
    }

    /**
     * Gets the attribute value for CaseNumber, using the alias name CaseNumber.
     * @return the CaseNumber
     */
    public String getCaseNumber() {
        return (String)getAttributeInternal(CASENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CaseNumber.
     * @param value value to set the CaseNumber
     */
    public void setCaseNumber(String value) {
        setAttributeInternal(CASENUMBER, value);
    }

    /**
     * Gets the attribute value for SubmittedDate, using the alias name SubmittedDate.
     * @return the SubmittedDate
     */
    public Date getSubmittedDate() {
        return (Date)getAttributeInternal(SUBMITTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmittedDate.
     * @param value value to set the SubmittedDate
     */
    public void setSubmittedDate(Date value) {
        setAttributeInternal(SUBMITTEDDATE, value);
    }

    /**
     * Gets the attribute value for DocketNumber, using the alias name DocketNumber.
     * @return the DocketNumber
     */
    public String getDocketNumber() {
        return (String)getAttributeInternal(DOCKETNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocketNumber.
     * @param value value to set the DocketNumber
     */
    public void setDocketNumber(String value) {
        setAttributeInternal(DOCKETNUMBER, value);
    }

    /**
     * Gets the attribute value for DocketDate, using the alias name DocketDate.
     * @return the DocketDate
     */
    public Date getDocketDate() {
        return (Date)getAttributeInternal(DOCKETDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocketDate.
     * @param value value to set the DocketDate
     */
    public void setDocketDate(Date value) {
        setAttributeInternal(DOCKETDATE, value);
    }

    /**
     * Gets the attribute value for HearingResult, using the alias name HearingResult.
     * @return the HearingResult
     */
    public String getHearingResult() {
        return (String)getAttributeInternal(HEARINGRESULT);
    }

    /**
     * Sets <code>value</code> as the attribute value for HearingResult.
     * @param value value to set the HearingResult
     */
    public void setHearingResult(String value) {
        setAttributeInternal(HEARINGRESULT, value);
    }

    /**
     * Gets the attribute value for SettlementAmt, using the alias name SettlementAmt.
     * @return the SettlementAmt
     */
    public Number getSettlementAmt() {
        return (Number)getAttributeInternal(SETTLEMENTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SettlementAmt.
     * @param value value to set the SettlementAmt
     */
    public void setSettlementAmt(Number value) {
        setAttributeInternal(SETTLEMENTAMT, value);
    }

    /**
     * Gets the attribute value for Notes, using the alias name Notes.
     * @return the Notes
     */
    public String getNotes() {
        return (String)getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Notes.
     * @param value value to set the Notes
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Stic, using the alias name Stic.
     * @return the Stic
     */
    public String getStic() {
        return (String)getAttributeInternal(STIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Stic.
     * @param value value to set the Stic
     */
    public void setStic(String value) {
        setAttributeInternal(STIC, value);
    }

    /**
     * Gets the attribute value for Plant, using the alias name Plant.
     * @return the Plant
     */
    public String getPlant() {
        return (String)getAttributeInternal(PLANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plant.
     * @param value value to set the Plant
     */
    public void setPlant(String value) {
        setAttributeInternal(PLANT, value);
    }

    /**
     * Gets the attribute value for Outby, using the alias name Outby.
     * @return the Outby
     */
    public String getOutby() {
        return (String)getAttributeInternal(OUTBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Outby.
     * @param value value to set the Outby
     */
    public void setOutby(String value) {
        setAttributeInternal(OUTBY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param violationId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number violationId) {
        return new Key(new Object[]{violationId});
    }


}
