package com.ceix.ehs.model.entities;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 10 19:10:28 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixEhsClinicalLogEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ClinicalId {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getClinicalId();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setClinicalId((Number)value);
            }
        }
        ,
        IncidentHeaderId {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getIncidentHeaderId();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setIncidentHeaderId((Number)value);
            }
        }
        ,
        MedicalMeasure {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getMedicalMeasure();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setMedicalMeasure((String)value);
            }
        }
        ,
        Hospital {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getHospital();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setHospital((String)value);
            }
        }
        ,
        OrderTreatment {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getOrderTreatment();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setOrderTreatment((String)value);
            }
        }
        ,
        Diagnosis {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getDiagnosis();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setDiagnosis((String)value);
            }
        }
        ,
        InjuryType {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getInjuryType();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setInjuryType((String)value);
            }
        }
        ,
        BodyPart {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getBodyPart();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setBodyPart((String)value);
            }
        }
        ,
        BodyPartDescription {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getBodyPartDescription();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setBodyPartDescription((String)value);
            }
        }
        ,
        ReturnToWork {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getReturnToWork();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setReturnToWork((String)value);
            }
        }
        ,
        ReturnDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getReturnDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setReturnDate((Date)value);
            }
        }
        ,
        FirstDayMissed {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getFirstDayMissed();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setFirstDayMissed((Date)value);
            }
        }
        ,
        TransDutyStartDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getTransDutyStartDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setTransDutyStartDate((Date)value);
            }
        }
        ,
        TransDutyEndDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getTransDutyEndDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setTransDutyEndDate((Date)value);
            }
        }
        ,
        TransDutyComments {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getTransDutyComments();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setTransDutyComments((String)value);
            }
        }
        ,
        ClinHealthNotifDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getClinHealthNotifDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setClinHealthNotifDate((Date)value);
            }
        }
        ,
        PhysicianName {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getPhysicianName();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setPhysicianName((String)value);
            }
        }
        ,
        NextOffVisitDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getNextOffVisitDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setNextOffVisitDate((Date)value);
            }
        }
        ,
        Tpa {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getTpa();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setTpa((String)value);
            }
        }
        ,
        TpaContact {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getTpaContact();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setTpaContact((String)value);
            }
        }
        ,
        WorkerPolicyNum {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getWorkerPolicyNum();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setWorkerPolicyNum((String)value);
            }
        }
        ,
        Comments {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getComments();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        TpaDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getTpaDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setTpaDate((Date)value);
            }
        }
        ,
        EmployeeId {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getEmployeeId();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setEmployeeId((Number)value);
            }
        }
        ,
        Bat {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getBat();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setBat((String)value);
            }
        }
        ,
        DaComments {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getDaComments();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setDaComments((String)value);
            }
        }
        ,
        DaResultsDate {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getDaResultsDate();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setDaResultsDate((Date)value);
            }
        }
        ,
        Uds {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getUds();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setUds((String)value);
            }
        }
        ,
        ReasonQInjury {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getReasonQInjury();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setReasonQInjury((String)value);
            }
        }
        ,
        Rtw {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getRtw();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setRtw((String)value);
            }
        }
        ,
        CeixEhsIncidentHeader {
            public Object get(CeixEhsClinicalLogEOImpl obj) {
                return obj.getCeixEhsIncidentHeader();
            }

            public void put(CeixEhsClinicalLogEOImpl obj, Object value) {
                obj.setCeixEhsIncidentHeader((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CeixEhsClinicalLogEOImpl object);

        public abstract void put(CeixEhsClinicalLogEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CLINICALID = AttributesEnum.ClinicalId.index();
    public static final int INCIDENTHEADERID = AttributesEnum.IncidentHeaderId.index();
    public static final int MEDICALMEASURE = AttributesEnum.MedicalMeasure.index();
    public static final int HOSPITAL = AttributesEnum.Hospital.index();
    public static final int ORDERTREATMENT = AttributesEnum.OrderTreatment.index();
    public static final int DIAGNOSIS = AttributesEnum.Diagnosis.index();
    public static final int INJURYTYPE = AttributesEnum.InjuryType.index();
    public static final int BODYPART = AttributesEnum.BodyPart.index();
    public static final int BODYPARTDESCRIPTION = AttributesEnum.BodyPartDescription.index();
    public static final int RETURNTOWORK = AttributesEnum.ReturnToWork.index();
    public static final int RETURNDATE = AttributesEnum.ReturnDate.index();
    public static final int FIRSTDAYMISSED = AttributesEnum.FirstDayMissed.index();
    public static final int TRANSDUTYSTARTDATE = AttributesEnum.TransDutyStartDate.index();
    public static final int TRANSDUTYENDDATE = AttributesEnum.TransDutyEndDate.index();
    public static final int TRANSDUTYCOMMENTS = AttributesEnum.TransDutyComments.index();
    public static final int CLINHEALTHNOTIFDATE = AttributesEnum.ClinHealthNotifDate.index();
    public static final int PHYSICIANNAME = AttributesEnum.PhysicianName.index();
    public static final int NEXTOFFVISITDATE = AttributesEnum.NextOffVisitDate.index();
    public static final int TPA = AttributesEnum.Tpa.index();
    public static final int TPACONTACT = AttributesEnum.TpaContact.index();
    public static final int WORKERPOLICYNUM = AttributesEnum.WorkerPolicyNum.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int TPADATE = AttributesEnum.TpaDate.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int BAT = AttributesEnum.Bat.index();
    public static final int DACOMMENTS = AttributesEnum.DaComments.index();
    public static final int DARESULTSDATE = AttributesEnum.DaResultsDate.index();
    public static final int UDS = AttributesEnum.Uds.index();
    public static final int REASONQINJURY = AttributesEnum.ReasonQInjury.index();
    public static final int RTW = AttributesEnum.Rtw.index();
    public static final int CEIXEHSINCIDENTHEADER = AttributesEnum.CeixEhsIncidentHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CeixEhsClinicalLogEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.ceix.ehs.model.entities.CeixEhsClinicalLogEO");
    }

    /**
     * Gets the attribute value for ClinicalId, using the alias name ClinicalId.
     * @return the ClinicalId
     */
    public Number getClinicalId() {
        return (Number)getAttributeInternal(CLINICALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClinicalId.
     * @param value value to set the ClinicalId
     */
    public void setClinicalId(Number value) {
        setAttributeInternal(CLINICALID, value);
    }

    /**
     * Gets the attribute value for IncidentHeaderId, using the alias name IncidentHeaderId.
     * @return the IncidentHeaderId
     */
    public Number getIncidentHeaderId() {
        return (Number)getAttributeInternal(INCIDENTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncidentHeaderId.
     * @param value value to set the IncidentHeaderId
     */
    public void setIncidentHeaderId(Number value) {
        setAttributeInternal(INCIDENTHEADERID, value);
    }

    /**
     * Gets the attribute value for MedicalMeasure, using the alias name MedicalMeasure.
     * @return the MedicalMeasure
     */
    public String getMedicalMeasure() {
        return (String)getAttributeInternal(MEDICALMEASURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MedicalMeasure.
     * @param value value to set the MedicalMeasure
     */
    public void setMedicalMeasure(String value) {
        setAttributeInternal(MEDICALMEASURE, value);
    }

    /**
     * Gets the attribute value for Hospital, using the alias name Hospital.
     * @return the Hospital
     */
    public String getHospital() {
        return (String)getAttributeInternal(HOSPITAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hospital.
     * @param value value to set the Hospital
     */
    public void setHospital(String value) {
        setAttributeInternal(HOSPITAL, value);
    }

    /**
     * Gets the attribute value for OrderTreatment, using the alias name OrderTreatment.
     * @return the OrderTreatment
     */
    public String getOrderTreatment() {
        return (String)getAttributeInternal(ORDERTREATMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderTreatment.
     * @param value value to set the OrderTreatment
     */
    public void setOrderTreatment(String value) {
        setAttributeInternal(ORDERTREATMENT, value);
    }

    /**
     * Gets the attribute value for Diagnosis, using the alias name Diagnosis.
     * @return the Diagnosis
     */
    public String getDiagnosis() {
        return (String)getAttributeInternal(DIAGNOSIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Diagnosis.
     * @param value value to set the Diagnosis
     */
    public void setDiagnosis(String value) {
        setAttributeInternal(DIAGNOSIS, value);
    }

    /**
     * Gets the attribute value for InjuryType, using the alias name InjuryType.
     * @return the InjuryType
     */
    public String getInjuryType() {
        return (String)getAttributeInternal(INJURYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InjuryType.
     * @param value value to set the InjuryType
     */
    public void setInjuryType(String value) {
        setAttributeInternal(INJURYTYPE, value);
    }

    /**
     * Gets the attribute value for BodyPart, using the alias name BodyPart.
     * @return the BodyPart
     */
    public String getBodyPart() {
        return (String)getAttributeInternal(BODYPART);
    }

    /**
     * Sets <code>value</code> as the attribute value for BodyPart.
     * @param value value to set the BodyPart
     */
    public void setBodyPart(String value) {
        setAttributeInternal(BODYPART, value);
    }

    /**
     * Gets the attribute value for BodyPartDescription, using the alias name BodyPartDescription.
     * @return the BodyPartDescription
     */
    public String getBodyPartDescription() {
        return (String)getAttributeInternal(BODYPARTDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BodyPartDescription.
     * @param value value to set the BodyPartDescription
     */
    public void setBodyPartDescription(String value) {
        setAttributeInternal(BODYPARTDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ReturnToWork, using the alias name ReturnToWork.
     * @return the ReturnToWork
     */
    public String getReturnToWork() {
        return (String)getAttributeInternal(RETURNTOWORK);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReturnToWork.
     * @param value value to set the ReturnToWork
     */
    public void setReturnToWork(String value) {
        setAttributeInternal(RETURNTOWORK, value);
    }

    /**
     * Gets the attribute value for ReturnDate, using the alias name ReturnDate.
     * @return the ReturnDate
     */
    public Date getReturnDate() {
        return (Date)getAttributeInternal(RETURNDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReturnDate.
     * @param value value to set the ReturnDate
     */
    public void setReturnDate(Date value) {
        setAttributeInternal(RETURNDATE, value);
    }

    /**
     * Gets the attribute value for FirstDayMissed, using the alias name FirstDayMissed.
     * @return the FirstDayMissed
     */
    public Date getFirstDayMissed() {
        return (Date)getAttributeInternal(FIRSTDAYMISSED);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstDayMissed.
     * @param value value to set the FirstDayMissed
     */
    public void setFirstDayMissed(Date value) {
        setAttributeInternal(FIRSTDAYMISSED, value);
    }

    /**
     * Gets the attribute value for TransDutyStartDate, using the alias name TransDutyStartDate.
     * @return the TransDutyStartDate
     */
    public Date getTransDutyStartDate() {
        return (Date)getAttributeInternal(TRANSDUTYSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransDutyStartDate.
     * @param value value to set the TransDutyStartDate
     */
    public void setTransDutyStartDate(Date value) {
        setAttributeInternal(TRANSDUTYSTARTDATE, value);
    }

    /**
     * Gets the attribute value for TransDutyEndDate, using the alias name TransDutyEndDate.
     * @return the TransDutyEndDate
     */
    public Date getTransDutyEndDate() {
        return (Date)getAttributeInternal(TRANSDUTYENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransDutyEndDate.
     * @param value value to set the TransDutyEndDate
     */
    public void setTransDutyEndDate(Date value) {
        setAttributeInternal(TRANSDUTYENDDATE, value);
    }

    /**
     * Gets the attribute value for TransDutyComments, using the alias name TransDutyComments.
     * @return the TransDutyComments
     */
    public String getTransDutyComments() {
        return (String)getAttributeInternal(TRANSDUTYCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransDutyComments.
     * @param value value to set the TransDutyComments
     */
    public void setTransDutyComments(String value) {
        setAttributeInternal(TRANSDUTYCOMMENTS, value);
    }

    /**
     * Gets the attribute value for ClinHealthNotifDate, using the alias name ClinHealthNotifDate.
     * @return the ClinHealthNotifDate
     */
    public Date getClinHealthNotifDate() {
        return (Date)getAttributeInternal(CLINHEALTHNOTIFDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClinHealthNotifDate.
     * @param value value to set the ClinHealthNotifDate
     */
    public void setClinHealthNotifDate(Date value) {
        setAttributeInternal(CLINHEALTHNOTIFDATE, value);
    }

    /**
     * Gets the attribute value for PhysicianName, using the alias name PhysicianName.
     * @return the PhysicianName
     */
    public String getPhysicianName() {
        return (String)getAttributeInternal(PHYSICIANNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhysicianName.
     * @param value value to set the PhysicianName
     */
    public void setPhysicianName(String value) {
        setAttributeInternal(PHYSICIANNAME, value);
    }

    /**
     * Gets the attribute value for NextOffVisitDate, using the alias name NextOffVisitDate.
     * @return the NextOffVisitDate
     */
    public Date getNextOffVisitDate() {
        return (Date)getAttributeInternal(NEXTOFFVISITDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextOffVisitDate.
     * @param value value to set the NextOffVisitDate
     */
    public void setNextOffVisitDate(Date value) {
        setAttributeInternal(NEXTOFFVISITDATE, value);
    }

    /**
     * Gets the attribute value for Tpa, using the alias name Tpa.
     * @return the Tpa
     */
    public String getTpa() {
        return (String)getAttributeInternal(TPA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Tpa.
     * @param value value to set the Tpa
     */
    public void setTpa(String value) {
        setAttributeInternal(TPA, value);
    }

    /**
     * Gets the attribute value for TpaContact, using the alias name TpaContact.
     * @return the TpaContact
     */
    public String getTpaContact() {
        return (String)getAttributeInternal(TPACONTACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TpaContact.
     * @param value value to set the TpaContact
     */
    public void setTpaContact(String value) {
        setAttributeInternal(TPACONTACT, value);
    }

    /**
     * Gets the attribute value for WorkerPolicyNum, using the alias name WorkerPolicyNum.
     * @return the WorkerPolicyNum
     */
    public String getWorkerPolicyNum() {
        return (String)getAttributeInternal(WORKERPOLICYNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkerPolicyNum.
     * @param value value to set the WorkerPolicyNum
     */
    public void setWorkerPolicyNum(String value) {
        setAttributeInternal(WORKERPOLICYNUM, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for TpaDate, using the alias name TpaDate.
     * @return the TpaDate
     */
    public Date getTpaDate() {
        return (Date)getAttributeInternal(TPADATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TpaDate.
     * @param value value to set the TpaDate
     */
    public void setTpaDate(Date value) {
        setAttributeInternal(TPADATE, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the EmployeeId
     */
    public Number getEmployeeId() {
        return (Number)getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for Bat, using the alias name Bat.
     * @return the Bat
     */
    public String getBat() {
        return (String)getAttributeInternal(BAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bat.
     * @param value value to set the Bat
     */
    public void setBat(String value) {
        setAttributeInternal(BAT, value);
    }

    /**
     * Gets the attribute value for DaComments, using the alias name DaComments.
     * @return the DaComments
     */
    public String getDaComments() {
        return (String)getAttributeInternal(DACOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DaComments.
     * @param value value to set the DaComments
     */
    public void setDaComments(String value) {
        setAttributeInternal(DACOMMENTS, value);
    }

    /**
     * Gets the attribute value for DaResultsDate, using the alias name DaResultsDate.
     * @return the DaResultsDate
     */
    public Date getDaResultsDate() {
        return (Date)getAttributeInternal(DARESULTSDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DaResultsDate.
     * @param value value to set the DaResultsDate
     */
    public void setDaResultsDate(Date value) {
        setAttributeInternal(DARESULTSDATE, value);
    }

    /**
     * Gets the attribute value for Uds, using the alias name Uds.
     * @return the Uds
     */
    public String getUds() {
        return (String)getAttributeInternal(UDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uds.
     * @param value value to set the Uds
     */
    public void setUds(String value) {
        setAttributeInternal(UDS, value);
    }

    /**
     * Gets the attribute value for ReasonQInjury, using the alias name ReasonQInjury.
     * @return the ReasonQInjury
     */
    public String getReasonQInjury() {
        return (String)getAttributeInternal(REASONQINJURY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReasonQInjury.
     * @param value value to set the ReasonQInjury
     */
    public void setReasonQInjury(String value) {
        setAttributeInternal(REASONQINJURY, value);
    }

    /**
     * Gets the attribute value for Rtw, using the alias name Rtw.
     * @return the Rtw
     */
    public String getRtw() {
        return (String)getAttributeInternal(RTW);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rtw.
     * @param value value to set the Rtw
     */
    public void setRtw(String value) {
        setAttributeInternal(RTW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getCeixEhsIncidentHeader() {
        return (EntityImpl)getAttributeInternal(CEIXEHSINCIDENTHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setCeixEhsIncidentHeader(EntityImpl value) {
        setAttributeInternal(CEIXEHSINCIDENTHEADER, value);
    }

    /**
     * @param clinicalId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number clinicalId) {
        return new Key(new Object[]{clinicalId});
    }


}
