package com.ceix.ehs.model.entities;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 22 05:28:31 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixEhsIncidentViolationAttachmentEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CeixEhsIncidentViolationAttachmentEODefImpl() {
    }
}
