package com.ceix.geolabs.model.services.common.serviceinterface;


import com.ceix.geolabs.model.view.common.WSResultPSDO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 27 14:40:28 IST 2018
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/com/ceix/geolabs/model/services/common/", name = "GeoLabsReportLoadService",
                    wsdlLocation =
                    "com/ceix/geolabs/model/services/common/serviceinterface/GeoLabsReportLoadService.wsdl")
@SDODatabinding(schemaLocation = "com/ceix/geolabs/model/services/common/serviceinterface/GeoLabsReportLoadService.xsd")
public interface GeoLabsReportLoadService {


    public static final String NAME = "{/com/ceix/geolabs/model/services/common/}GeoLabsReportLoadService";

    /**
     * Exported method execute from GeoLabsReportLoadAM.
     */
    @WebMethod(action = "/com/ceix/geolabs/model/services/common/execute", operationName = "execute")
    @RequestWrapper(targetNamespace = "/com/ceix/geolabs/model/services/common/types/", localName = "execute")
    @ResponseWrapper(targetNamespace = "/com/ceix/geolabs/model/services/common/types/", localName = "executeResponse")
    @WebResult(name = "result")
    List<WSResultPSDO> execute() throws ServiceException;


    /**
     * Exported method executeItmann from GeoLabsReportLoadAM.
     */
    @WebMethod(action = "/com/ceix/geolabs/model/services/common/executeItmann", operationName = "executeItmann")
    @RequestWrapper(targetNamespace = "/com/ceix/geolabs/model/services/common/types/", localName = "executeItmann")
    @ResponseWrapper(targetNamespace = "/com/ceix/geolabs/model/services/common/types/",
                     localName = "executeItmannResponse")
    @WebResult(name = "result")
    List<WSResultPSDO> executeItmann() throws ServiceException;
}
