package com.ceix.waybill_purch_coal_import.model.views;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 29 20:53:02 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CEIXStsWaybillBtmoreLinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DeliveryLineId {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getDeliveryLineId();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setDeliveryLineId((Number)value);
            }
        }
        ,
        ShipToInformation {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getShipToInformation();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setShipToInformation((String)value);
            }
        }
        ,
        DumpSequence {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getDumpSequence();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setDumpSequence((Number)value);
            }
        }
        ,
        RailRoad {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getRailRoad();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setRailRoad((String)value);
            }
        }
        ,
        CarNumber {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getCarNumber();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setCarNumber((String)value);
            }
        }
        ,
        CarWeight {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getCarWeight();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setCarWeight((String)value);
            }
        }
        ,
        TrainNumber {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getTrainNumber();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setTrainNumber((String)value);
            }
        }
        ,
        DeliveryHeaderId {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getDeliveryHeaderId();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setDeliveryHeaderId((Number)value);
            }
        }
        ,
        SalesOrderNumber {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getSalesOrderNumber();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setSalesOrderNumber((String)value);
            }
        }
        ,
        UnitTrainNumber {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getUnitTrainNumber();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setUnitTrainNumber((String)value);
            }
        }
        ,
        ScheduleDate {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getScheduleDate();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setScheduleDate((Date)value);
            }
        }
        ,
        ShipmentNumber {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getShipmentNumber();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setShipmentNumber((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        NewCarPrefix {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getNewCarPrefix();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setNewCarPrefix((String)value);
            }
        }
        ,
        Type {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getType();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setType((String)value);
            }
        }
        ,
        Uom {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getUom();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        CarPrefix {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getCarPrefix();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setCarPrefix((String)value);
            }
        }
        ,
        WeightInTons {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getWeightInTons();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setWeightInTons((String)value);
            }
        }
        ,
        SubInventory {
            public Object get(CEIXStsWaybillBtmoreLinesVORowImpl obj) {
                return obj.getSubInventory();
            }

            public void put(CEIXStsWaybillBtmoreLinesVORowImpl obj,
                            Object value) {
                obj.setSubInventory((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CEIXStsWaybillBtmoreLinesVORowImpl object);

        public abstract void put(CEIXStsWaybillBtmoreLinesVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DELIVERYLINEID = AttributesEnum.DeliveryLineId.index();
    public static final int SHIPTOINFORMATION = AttributesEnum.ShipToInformation.index();
    public static final int DUMPSEQUENCE = AttributesEnum.DumpSequence.index();
    public static final int RAILROAD = AttributesEnum.RailRoad.index();
    public static final int CARNUMBER = AttributesEnum.CarNumber.index();
    public static final int CARWEIGHT = AttributesEnum.CarWeight.index();
    public static final int TRAINNUMBER = AttributesEnum.TrainNumber.index();
    public static final int DELIVERYHEADERID = AttributesEnum.DeliveryHeaderId.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int UNITTRAINNUMBER = AttributesEnum.UnitTrainNumber.index();
    public static final int SCHEDULEDATE = AttributesEnum.ScheduleDate.index();
    public static final int SHIPMENTNUMBER = AttributesEnum.ShipmentNumber.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int NEWCARPREFIX = AttributesEnum.NewCarPrefix.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int CARPREFIX = AttributesEnum.CarPrefix.index();
    public static final int WEIGHTINTONS = AttributesEnum.WeightInTons.index();
    public static final int SUBINVENTORY = AttributesEnum.SubInventory.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CEIXStsWaybillBtmoreLinesVORowImpl() {
    }

    /**
     * Gets CEIXStsWaybillBtmoreLinesEO entity object.
     * @return the CEIXStsWaybillBtmoreLinesEO
     */
    public EntityImpl getCEIXStsWaybillBtmoreLinesEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DELIVERY_LINE_ID using the alias name DeliveryLineId.
     * @return the DELIVERY_LINE_ID
     */
    public Number getDeliveryLineId() {
        return (Number) getAttributeInternal(DELIVERYLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_LINE_ID using the alias name DeliveryLineId.
     * @param value value to set the DELIVERY_LINE_ID
     */
    public void setDeliveryLineId(Number value) {
        setAttributeInternal(DELIVERYLINEID, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_INFORMATION using the alias name ShipToInformation.
     * @return the SHIP_TO_INFORMATION
     */
    public String getShipToInformation() {
        return (String) getAttributeInternal(SHIPTOINFORMATION);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_INFORMATION using the alias name ShipToInformation.
     * @param value value to set the SHIP_TO_INFORMATION
     */
    public void setShipToInformation(String value) {
        setAttributeInternal(SHIPTOINFORMATION, value);
    }

    /**
     * Gets the attribute value for DUMP_SEQUENCE using the alias name DumpSequence.
     * @return the DUMP_SEQUENCE
     */
    public Number getDumpSequence() {
        return (Number) getAttributeInternal(DUMPSEQUENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUMP_SEQUENCE using the alias name DumpSequence.
     * @param value value to set the DUMP_SEQUENCE
     */
    public void setDumpSequence(Number value) {
        setAttributeInternal(DUMPSEQUENCE, value);
    }

    /**
     * Gets the attribute value for RAIL_ROAD using the alias name RailRoad.
     * @return the RAIL_ROAD
     */
    public String getRailRoad() {
        return (String) getAttributeInternal(RAILROAD);
    }

    /**
     * Sets <code>value</code> as attribute value for RAIL_ROAD using the alias name RailRoad.
     * @param value value to set the RAIL_ROAD
     */
    public void setRailRoad(String value) {
        setAttributeInternal(RAILROAD, value);
    }

    /**
     * Gets the attribute value for CAR_NUMBER using the alias name CarNumber.
     * @return the CAR_NUMBER
     */
    public String getCarNumber() {
        return (String) getAttributeInternal(CARNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_NUMBER using the alias name CarNumber.
     * @param value value to set the CAR_NUMBER
     */
    public void setCarNumber(String value) {
        setAttributeInternal(CARNUMBER, value);
    }

    /**
     * Gets the attribute value for CAR_WEIGHT using the alias name CarWeight.
     * @return the CAR_WEIGHT
     */
    public String getCarWeight() {
        return (String) getAttributeInternal(CARWEIGHT);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_WEIGHT using the alias name CarWeight.
     * @param value value to set the CAR_WEIGHT
     */
    public void setCarWeight(String value) {
        setAttributeInternal(CARWEIGHT, value);
    }

    /**
     * Gets the attribute value for TRAIN_NUMBER using the alias name TrainNumber.
     * @return the TRAIN_NUMBER
     */
    public String getTrainNumber() {
        return (String) getAttributeInternal(TRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAIN_NUMBER using the alias name TrainNumber.
     * @param value value to set the TRAIN_NUMBER
     */
    public void setTrainNumber(String value) {
        setAttributeInternal(TRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for DELIVERY_HEADER_ID using the alias name DeliveryHeaderId.
     * @return the DELIVERY_HEADER_ID
     */
    public Number getDeliveryHeaderId() {
        return (Number) getAttributeInternal(DELIVERYHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_HEADER_ID using the alias name DeliveryHeaderId.
     * @param value value to set the DELIVERY_HEADER_ID
     */
    public void setDeliveryHeaderId(Number value) {
        setAttributeInternal(DELIVERYHEADERID, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @return the SALES_ORDER_NUMBER
     */
    public String getSalesOrderNumber() {
        return (String) getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @param value value to set the SALES_ORDER_NUMBER
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for UNIT_TRAIN_NUMBER using the alias name UnitTrainNumber.
     * @return the UNIT_TRAIN_NUMBER
     */
    public String getUnitTrainNumber() {
        return (String) getAttributeInternal(UNITTRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_TRAIN_NUMBER using the alias name UnitTrainNumber.
     * @param value value to set the UNIT_TRAIN_NUMBER
     */
    public void setUnitTrainNumber(String value) {
        setAttributeInternal(UNITTRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for SCHEDULE_DATE using the alias name ScheduleDate.
     * @return the SCHEDULE_DATE
     */
    public Date getScheduleDate() {
        return (Date) getAttributeInternal(SCHEDULEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEDULE_DATE using the alias name ScheduleDate.
     * @param value value to set the SCHEDULE_DATE
     */
    public void setScheduleDate(Date value) {
        setAttributeInternal(SCHEDULEDATE, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber.
     * @return the SHIPMENT_NUMBER
     */
    public String getShipmentNumber() {
        return (String) getAttributeInternal(SHIPMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber.
     * @param value value to set the SHIPMENT_NUMBER
     */
    public void setShipmentNumber(String value) {
        setAttributeInternal(SHIPMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for NEW_CAR_PREFIX using the alias name NewCarPrefix.
     * @return the NEW_CAR_PREFIX
     */
    public String getNewCarPrefix() {
        return (String) getAttributeInternal(NEWCARPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_CAR_PREFIX using the alias name NewCarPrefix.
     * @param value value to set the NEW_CAR_PREFIX
     */
    public void setNewCarPrefix(String value) {
        setAttributeInternal(NEWCARPREFIX, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for CAR_PREFIX using the alias name CarPrefix.
     * @return the CAR_PREFIX
     */
    public String getCarPrefix() {
        return (String) getAttributeInternal(CARPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_PREFIX using the alias name CarPrefix.
     * @param value value to set the CAR_PREFIX
     */
    public void setCarPrefix(String value) {
        setAttributeInternal(CARPREFIX, value);
    }

    /**
     * Gets the attribute value for WEIGHT_IN_TONS using the alias name WeightInTons.
     * @return the WEIGHT_IN_TONS
     */
    public String getWeightInTons() {
        return (String) getAttributeInternal(WEIGHTINTONS);
    }

    /**
     * Sets <code>value</code> as attribute value for WEIGHT_IN_TONS using the alias name WeightInTons.
     * @param value value to set the WEIGHT_IN_TONS
     */
    public void setWeightInTons(String value) {
        setAttributeInternal(WEIGHTINTONS, value);
    }

    /**
     * Gets the attribute value for SUB_INVENTORY using the alias name SubInventory.
     * @return the SUB_INVENTORY
     */
    public String getSubInventory() {
        return (String) getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_INVENTORY using the alias name SubInventory.
     * @param value value to set the SUB_INVENTORY
     */
    public void setSubInventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
