package com.ceix.waybill_purch_coal_import.model.views;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 29 20:52:52 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CEIXStsWaybillBtmoreHdrVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CEIXStsWaybillBtmoreHdrVOImpl() {
    }

    /**
     * Returns the variable value for dumpDt.
     * @return variable value for dumpDt
     */
    public Date getdumpDt() {
        return (Date)ensureVariableManager().getVariableValue("dumpDt");
    }

    /**
     * Sets <code>value</code> for variable dumpDt.
     * @param value value to bind as dumpDt
     */
    public void setdumpDt(Date value) {
        ensureVariableManager().setVariableValue("dumpDt", value);
    }

    /**
     * Returns the variable value for trainNum.
     * @return variable value for trainNum
     */
    public String gettrainNum() {
        return (String)ensureVariableManager().getVariableValue("trainNum");
    }

    /**
     * Sets <code>value</code> for variable trainNum.
     * @param value value to bind as trainNum
     */
    public void settrainNum(String value) {
        ensureVariableManager().setVariableValue("trainNum", value);
    }
}
