package com.ceix.stsrail.model.views;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 30 14:49:55 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixStsRailSchedulesOrdNumMassUpdateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CeixStsRailSchedulesOrdNumMassUpdateVOImpl() {
    }

    /**
     * Returns the variable value for trainId.
     * @return variable value for trainId
     */
    public String gettrainId() {
        return (String)ensureVariableManager().getVariableValue("trainId");
    }

    /**
     * Sets <code>value</code> for variable trainId.
     * @param value value to bind as trainId
     */
    public void settrainId(String value) {
        ensureVariableManager().setVariableValue("trainId", value);
    }

    /**
     * Returns the variable value for loadDtStart.
     * @return variable value for loadDtStart
     */
    public Date getloadDtStart() {
        return (Date)ensureVariableManager().getVariableValue("loadDtStart");
    }

    /**
     * Sets <code>value</code> for variable loadDtStart.
     * @param value value to bind as loadDtStart
     */
    public void setloadDtStart(Date value) {
        ensureVariableManager().setVariableValue("loadDtStart", value);
    }

    /**
     * Returns the variable value for loadDtEnd.
     * @return variable value for loadDtEnd
     */
    public Date getloadDtEnd() {
        return (Date)ensureVariableManager().getVariableValue("loadDtEnd");
    }

    /**
     * Sets <code>value</code> for variable loadDtEnd.
     * @param value value to bind as loadDtEnd
     */
    public void setloadDtEnd(Date value) {
        ensureVariableManager().setVariableValue("loadDtEnd", value);
    }

    /**
     * Returns the variable value for dstnation.
     * @return variable value for dstnation
     */
    public String getdstnation() {
        return (String)ensureVariableManager().getVariableValue("dstnation");
    }

    /**
     * Sets <code>value</code> for variable dstnation.
     * @param value value to bind as dstnation
     */
    public void setdstnation(String value) {
        ensureVariableManager().setVariableValue("dstnation", value);
    }
}
