package com.ceix.stsrail.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 08 17:56:53 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MineLocationLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MineLocationLOVImpl() {
    }
}

