package com.ceix.waybill.model.entities;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 31 11:57:14 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixStsWaybillLinesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DeliveryLineId {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getDeliveryLineId();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setDeliveryLineId((Number) value);
            }
        }
        ,
        ShipToInformation {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getShipToInformation();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setShipToInformation((String) value);
            }
        }
        ,
        DumpSequence {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getDumpSequence();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setDumpSequence((Number) value);
            }
        }
        ,
        RailRoad {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getRailRoad();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setRailRoad((String) value);
            }
        }
        ,
        CarPrefix {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getCarPrefix();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setCarPrefix((String) value);
            }
        }
        ,
        CarNumber {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getCarNumber();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setCarNumber((String) value);
            }
        }
        ,
        CarWeight {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getCarWeight();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setCarWeight((String) value);
            }
        }
        ,
        Type {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getType();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setType((String) value);
            }
        }
        ,
        Uom {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getUom();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setUom((String) value);
            }
        }
        ,
        TrainNumber {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getTrainNumber();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setTrainNumber((String) value);
            }
        }
        ,
        DeliveryHeaderId {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getDeliveryHeaderId();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setDeliveryHeaderId((Number) value);
            }
        }
        ,
        SalesOrderNumber {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getSalesOrderNumber();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setSalesOrderNumber((String) value);
            }
        }
        ,
        NewTrainNumber {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getNewTrainNumber();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setNewTrainNumber((String) value);
            }
        }
        ,
        NewCarPrefix {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getNewCarPrefix();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setNewCarPrefix((String) value);
            }
        }
        ,
        NewCarNumber {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getNewCarNumber();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setNewCarNumber((String) value);
            }
        }
        ,
        ScheduleDate {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getScheduleDate();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setScheduleDate((Date) value);
            }
        }
        ,
        ShipmentNumber {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getShipmentNumber();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setShipmentNumber((String) value);
            }
        }
        ,
        ShippedQuantity {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getShippedQuantity();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setShippedQuantity((String) value);
            }
        }
        ,
        FreightCost {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getFreightCost();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setFreightCost((String) value);
            }
        }
        ,
        CreationDate {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getCreationDate();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WeightInTons {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getWeightInTons();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setWeightInTons((String) value);
            }
        }
        ,
        Comments {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getComments();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setComments((String) value);
            }
        }
        ,
        ProcessedFlag {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getProcessedFlag();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setProcessedFlag((String) value);
            }
        }
        ,
        TransferredFlag {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getTransferredFlag();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setTransferredFlag((String) value);
            }
        }
        ,
        SubInventory {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getSubInventory();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setSubInventory((String) value);
            }
        }
        ,
        Attribute1 {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getAttribute1();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttribute1((String) value);
            }
        }
        ,
        Attribute2 {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getAttribute2();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttribute2((String) value);
            }
        }
        ,
        Attribute3 {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getAttribute3();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setAttribute3((String) value);
            }
        }
        ,
        Destination {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getDestination();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setDestination((String) value);
            }
        }
        ,
        LoadOrigin {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getLoadOrigin();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setLoadOrigin((String) value);
            }
        }
        ,
        Straggler {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getStraggler();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setStraggler((String) value);
            }
        }
        ,
        Freight {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getFreight();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setFreight((String) value);
            }
        }
        ,
        DumpWeight {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getDumpWeight();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setDumpWeight((String) value);
            }
        }
        ,
        DumpedTons {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getDumpedTons();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setDumpedTons((String) value);
            }
        }
        ,
        ShipWeight {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getShipWeight();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setShipWeight((String) value);
            }
        }
        ,
        CeixStsWaybillHdrEO {
            protected Object get(CeixStsWaybillLinesEOImpl obj) {
                return obj.getCeixStsWaybillHdrEO();
            }

            protected void put(CeixStsWaybillLinesEOImpl obj, Object value) {
                obj.setCeixStsWaybillHdrEO((CeixStsWaybillHdrEOImpl) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(CeixStsWaybillLinesEOImpl object);

        protected abstract void put(CeixStsWaybillLinesEOImpl object, Object value);
    }


    public static final int DELIVERYLINEID = AttributesEnum.DeliveryLineId.index();
    public static final int SHIPTOINFORMATION = AttributesEnum.ShipToInformation.index();
    public static final int DUMPSEQUENCE = AttributesEnum.DumpSequence.index();
    public static final int RAILROAD = AttributesEnum.RailRoad.index();
    public static final int CARPREFIX = AttributesEnum.CarPrefix.index();
    public static final int CARNUMBER = AttributesEnum.CarNumber.index();
    public static final int CARWEIGHT = AttributesEnum.CarWeight.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int TRAINNUMBER = AttributesEnum.TrainNumber.index();
    public static final int DELIVERYHEADERID = AttributesEnum.DeliveryHeaderId.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int NEWTRAINNUMBER = AttributesEnum.NewTrainNumber.index();
    public static final int NEWCARPREFIX = AttributesEnum.NewCarPrefix.index();
    public static final int NEWCARNUMBER = AttributesEnum.NewCarNumber.index();
    public static final int SCHEDULEDATE = AttributesEnum.ScheduleDate.index();
    public static final int SHIPMENTNUMBER = AttributesEnum.ShipmentNumber.index();
    public static final int SHIPPEDQUANTITY = AttributesEnum.ShippedQuantity.index();
    public static final int FREIGHTCOST = AttributesEnum.FreightCost.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int WEIGHTINTONS = AttributesEnum.WeightInTons.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int PROCESSEDFLAG = AttributesEnum.ProcessedFlag.index();
    public static final int TRANSFERREDFLAG = AttributesEnum.TransferredFlag.index();
    public static final int SUBINVENTORY = AttributesEnum.SubInventory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int DESTINATION = AttributesEnum.Destination.index();
    public static final int LOADORIGIN = AttributesEnum.LoadOrigin.index();
    public static final int STRAGGLER = AttributesEnum.Straggler.index();
    public static final int FREIGHT = AttributesEnum.Freight.index();
    public static final int DUMPWEIGHT = AttributesEnum.DumpWeight.index();
    public static final int DUMPEDTONS = AttributesEnum.DumpedTons.index();
    public static final int SHIPWEIGHT = AttributesEnum.ShipWeight.index();
    public static final int CEIXSTSWAYBILLHDREO = AttributesEnum.CeixStsWaybillHdrEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CeixStsWaybillLinesEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.ceix.waybill.model.entities.CeixStsWaybillLinesEO");
    }


    /**
     * Gets the attribute value for DeliveryLineId, using the alias name DeliveryLineId.
     * @return the DeliveryLineId
     */
    public Number getDeliveryLineId() {
        return (Number)getAttributeInternal(DELIVERYLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryLineId.
     * @param value value to set the DeliveryLineId
     */
    public void setDeliveryLineId(Number value) {
        setAttributeInternal(DELIVERYLINEID, value);
    }

    /**
     * Gets the attribute value for ShipToInformation, using the alias name ShipToInformation.
     * @return the ShipToInformation
     */
    public String getShipToInformation() {
        return (String)getAttributeInternal(SHIPTOINFORMATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToInformation.
     * @param value value to set the ShipToInformation
     */
    public void setShipToInformation(String value) {
        setAttributeInternal(SHIPTOINFORMATION, value);
    }

    /**
     * Gets the attribute value for DumpSequence, using the alias name DumpSequence.
     * @return the DumpSequence
     */
    public Number getDumpSequence() {
        return (Number)getAttributeInternal(DUMPSEQUENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DumpSequence.
     * @param value value to set the DumpSequence
     */
    public void setDumpSequence(Number value) {
        setAttributeInternal(DUMPSEQUENCE, value);
    }

    /**
     * Gets the attribute value for RailRoad, using the alias name RailRoad.
     * @return the RailRoad
     */
    public String getRailRoad() {
        return (String)getAttributeInternal(RAILROAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for RailRoad.
     * @param value value to set the RailRoad
     */
    public void setRailRoad(String value) {
        setAttributeInternal(RAILROAD, value);
    }

    /**
     * Gets the attribute value for CarPrefix, using the alias name CarPrefix.
     * @return the CarPrefix
     */
    public String getCarPrefix() {
        return (String)getAttributeInternal(CARPREFIX);
    }

    /**
     * Sets <code>value</code> as the attribute value for CarPrefix.
     * @param value value to set the CarPrefix
     */
    public void setCarPrefix(String value) {
        setAttributeInternal(CARPREFIX, value);
    }

    /**
     * Gets the attribute value for CarNumber, using the alias name CarNumber.
     * @return the CarNumber
     */
    public String getCarNumber() {
        return (String)getAttributeInternal(CARNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CarNumber.
     * @param value value to set the CarNumber
     */
    public void setCarNumber(String value) {
        setAttributeInternal(CARNUMBER, value);
    }

    /**
     * Gets the attribute value for CarWeight, using the alias name CarWeight.
     * @return the CarWeight
     */
    public String getCarWeight() {
        return (String)getAttributeInternal(CARWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CarWeight.
     * @param value value to set the CarWeight
     */
    public void setCarWeight(String value) {
        setAttributeInternal(CARWEIGHT, value);
    }

    /**
     * Gets the attribute value for Type, using the alias name Type.
     * @return the Type
     */
    public String getType() {
        return (String)getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Type.
     * @param value value to set the Type
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String)getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for TrainNumber, using the alias name TrainNumber.
     * @return the TrainNumber
     */
    public String getTrainNumber() {
        return (String)getAttributeInternal(TRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrainNumber.
     * @param value value to set the TrainNumber
     */
    public void setTrainNumber(String value) {
        setAttributeInternal(TRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for DeliveryHeaderId, using the alias name DeliveryHeaderId.
     * @return the DeliveryHeaderId
     */
    public Number getDeliveryHeaderId() {
        return (Number)getAttributeInternal(DELIVERYHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryHeaderId.
     * @param value value to set the DeliveryHeaderId
     */
    public void setDeliveryHeaderId(Number value) {
        setAttributeInternal(DELIVERYHEADERID, value);
    }

    /**
     * Gets the attribute value for SalesOrderNumber, using the alias name SalesOrderNumber.
     * @return the SalesOrderNumber
     */
    public String getSalesOrderNumber() {
        return (String)getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesOrderNumber.
     * @param value value to set the SalesOrderNumber
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for NewTrainNumber, using the alias name NewTrainNumber.
     * @return the NewTrainNumber
     */
    public String getNewTrainNumber() {
        return (String)getAttributeInternal(NEWTRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewTrainNumber.
     * @param value value to set the NewTrainNumber
     */
    public void setNewTrainNumber(String value) {
        setAttributeInternal(NEWTRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for NewCarPrefix, using the alias name NewCarPrefix.
     * @return the NewCarPrefix
     */
    public String getNewCarPrefix() {
        return (String)getAttributeInternal(NEWCARPREFIX);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewCarPrefix.
     * @param value value to set the NewCarPrefix
     */
    public void setNewCarPrefix(String value) {
        setAttributeInternal(NEWCARPREFIX, value);
    }

    /**
     * Gets the attribute value for NewCarNumber, using the alias name NewCarNumber.
     * @return the NewCarNumber
     */
    public String getNewCarNumber() {
        return (String)getAttributeInternal(NEWCARNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewCarNumber.
     * @param value value to set the NewCarNumber
     */
    public void setNewCarNumber(String value) {
        setAttributeInternal(NEWCARNUMBER, value);
    }

    /**
     * Gets the attribute value for ScheduleDate, using the alias name ScheduleDate.
     * @return the ScheduleDate
     */
    public Date getScheduleDate() {
        return (Date)getAttributeInternal(SCHEDULEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScheduleDate.
     * @param value value to set the ScheduleDate
     */
    public void setScheduleDate(Date value) {
        setAttributeInternal(SCHEDULEDATE, value);
    }

    /**
     * Gets the attribute value for ShipmentNumber, using the alias name ShipmentNumber.
     * @return the ShipmentNumber
     */
    public String getShipmentNumber() {
        return (String)getAttributeInternal(SHIPMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentNumber.
     * @param value value to set the ShipmentNumber
     */
    public void setShipmentNumber(String value) {
        setAttributeInternal(SHIPMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for ShippedQuantity, using the alias name ShippedQuantity.
     * @return the ShippedQuantity
     */
    public String getShippedQuantity() {
        return (String)getAttributeInternal(SHIPPEDQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShippedQuantity.
     * @param value value to set the ShippedQuantity
     */
    public void setShippedQuantity(String value) {
        setAttributeInternal(SHIPPEDQUANTITY, value);
    }

    /**
     * Gets the attribute value for FreightCost, using the alias name FreightCost.
     * @return the FreightCost
     */
    public String getFreightCost() {
        return (String)getAttributeInternal(FREIGHTCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for FreightCost.
     * @param value value to set the FreightCost
     */
    public void setFreightCost(String value) {
        setAttributeInternal(FREIGHTCOST, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for WeightInTons, using the alias name WeightInTons.
     * @return the WeightInTons
     */
    public String getWeightInTons() {
        return (String)getAttributeInternal(WEIGHTINTONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeightInTons.
     * @param value value to set the WeightInTons
     */
    public void setWeightInTons(String value) {
        setAttributeInternal(WEIGHTINTONS, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ProcessedFlag, using the alias name ProcessedFlag.
     * @return the ProcessedFlag
     */
    public String getProcessedFlag() {
        return (String)getAttributeInternal(PROCESSEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessedFlag.
     * @param value value to set the ProcessedFlag
     */
    public void setProcessedFlag(String value) {
        setAttributeInternal(PROCESSEDFLAG, value);
    }

    /**
     * Gets the attribute value for TransferredFlag, using the alias name TransferredFlag.
     * @return the TransferredFlag
     */
    public String getTransferredFlag() {
        return (String)getAttributeInternal(TRANSFERREDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransferredFlag.
     * @param value value to set the TransferredFlag
     */
    public void setTransferredFlag(String value) {
        setAttributeInternal(TRANSFERREDFLAG, value);
    }

    /**
     * Gets the attribute value for SubInventory, using the alias name SubInventory.
     * @return the SubInventory
     */
    public String getSubInventory() {
        return (String)getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubInventory.
     * @param value value to set the SubInventory
     */
    public void setSubInventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the value of Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the value of Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the value of Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Destination, using the alias name Destination.
     * @return the value of Destination
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Destination.
     * @param value value to set the Destination
     */
    public void setDestination(String value) {
        setAttributeInternal(DESTINATION, value);
    }

    /**
     * Gets the attribute value for LoadOrigin, using the alias name LoadOrigin.
     * @return the value of LoadOrigin
     */
    public String getLoadOrigin() {
        return (String) getAttributeInternal(LOADORIGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoadOrigin.
     * @param value value to set the LoadOrigin
     */
    public void setLoadOrigin(String value) {
        setAttributeInternal(LOADORIGIN, value);
    }

    /**
     * Gets the attribute value for Straggler, using the alias name Straggler.
     * @return the value of Straggler
     */
    public String getStraggler() {
        return (String) getAttributeInternal(STRAGGLER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Straggler.
     * @param value value to set the Straggler
     */
    public void setStraggler(String value) {
        setAttributeInternal(STRAGGLER, value);
    }

    /**
     * Gets the attribute value for Freight, using the alias name Freight.
     * @return the value of Freight
     */
    public String getFreight() {
        return (String) getAttributeInternal(FREIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Freight.
     * @param value value to set the Freight
     */
    public void setFreight(String value) {
        setAttributeInternal(FREIGHT, value);
    }

    /**
     * Gets the attribute value for DumpWeight, using the alias name DumpWeight.
     * @return the value of DumpWeight
     */
    public String getDumpWeight() {
        return (String) getAttributeInternal(DUMPWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DumpWeight.
     * @param value value to set the DumpWeight
     */
    public void setDumpWeight(String value) {
        setAttributeInternal(DUMPWEIGHT, value);
    }

    /**
     * Gets the attribute value for DumpedTons, using the alias name DumpedTons.
     * @return the value of DumpedTons
     */
    public String getDumpedTons() {
        return (String) getAttributeInternal(DUMPEDTONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DumpedTons.
     * @param value value to set the DumpedTons
     */
    public void setDumpedTons(String value) {
        setAttributeInternal(DUMPEDTONS, value);
    }

    /**
     * Gets the attribute value for ShipWeight, using the alias name ShipWeight.
     * @return the value of ShipWeight
     */
    public String getShipWeight() {
        return (String) getAttributeInternal(SHIPWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipWeight.
     * @param value value to set the ShipWeight
     */
    public void setShipWeight(String value) {
        setAttributeInternal(SHIPWEIGHT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CeixStsWaybillHdrEOImpl.
     */
    public CeixStsWaybillHdrEOImpl getCeixStsWaybillHdrEO() {
        return (CeixStsWaybillHdrEOImpl)getAttributeInternal(CEIXSTSWAYBILLHDREO);
    }

    /**
     * Sets <code>value</code> as the associated entity CeixStsWaybillHdrEOImpl.
     */
    public void setCeixStsWaybillHdrEO(CeixStsWaybillHdrEOImpl value) {
        setAttributeInternal(CEIXSTSWAYBILLHDREO, value);
    }

    /**
     * @param deliveryLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number deliveryLineId) {
        return new Key(new Object[] { deliveryLineId });
    }


}
