package com.ceix.qualnetxmlgen.model.services.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 15 16:35:42 IST 2018
// ---------------------------------------------------------------------
public interface CEIXQualnetXMLGenAM extends ApplicationModule {
    
}
