package ceix.com.bc.am.server.serviceinterface;

import ceix.com.bc.am.CEIXShipNotificationAMImpl;
import ceix.com.bc.am.common.serviceinterface.CEIXShipNotificationAMService;

import java.lang.reflect.Method;

import java.util.HashMap;
import java.util.Map;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 22 15:32:45 IST 2020
// ---------------------------------------------------------------------
@Stateless(name = "ceix.com.bc.am.common.CEIXShipNotificationAMServiceBean",
           mappedName = "CEIXShipNotificationAMServiceBean")
@Remote(CEIXShipNotificationAMService.class)
@PortableWebService(targetNamespace = "/ceix/com/bc/am/common/", serviceName = "CEIXShipNotificationAMService",
                    portName = "CEIXShipNotificationAMServiceSoapHttpPort",
                    endpointInterface = "ceix.com.bc.am.common.serviceinterface.CEIXShipNotificationAMService")
@Interceptors({ ServiceContextInterceptor.class })
public class CEIXShipNotificationAMServiceImpl extends ServiceImpl implements CEIXShipNotificationAMService {
    private static boolean _isInited = false;
    private static final Map _map = new HashMap();

    /**
     * This is the default constructor (do not remove).
     */
    public CEIXShipNotificationAMServiceImpl() {
        init();
        setApplicationModuleDefName("ceix.com.bc.am.CEIXShipNotificationAM");
        setConfigurationName("CEIXShipNotificationAMService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (CEIXShipNotificationAMServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("ceix/com/bc/am/common/serviceinterface/",
                                                "CEIXShipNotificationAMService.xsd");
                _map.put("createPDFReport",
                         CEIXShipNotificationAMImpl.class.getMethod("createPDFReport", new Class[] { String.class }));
                _isInited = true;
            } catch (Throwable t) {
                ADFLogger.createADFLogger(Diagnostic.SERVINT_RT_LOGGER).severe(t);
            }
        }
    }

    /**
     * createPDFReport: generated method. Do not modify.
     */
    public String createPDFReport(String trainNumber) throws ServiceException {
        return (String) invokeCustom((Method) _map.get("createPDFReport"), new Object[] { trainNumber },
                                     new String[] { null }, false);
    }
}

