package com.ceix.geolabs.model.services.server.serviceinterface;


import com.ceix.geolabs.model.services.GeoLabsReportLoadAMImpl;
import com.ceix.geolabs.model.services.common.serviceinterface.GeoLabsReportLoadService;
import com.ceix.geolabs.model.view.common.WSResultPSDO;

import java.lang.reflect.Method;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.server.svc.ServicePermissionCheckInterceptor;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SecurityPolicy;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 27 14:40:28 IST 2018
// ---------------------------------------------------------------------
@Interceptors( { ServiceContextInterceptor.class, ServicePermissionCheckInterceptor.class })
@SecurityPolicy( { "oracle/wss_http_token_service_policy"})
@Stateless(name = "com.ceix.geolabs.model.services.common.GeoLabsReportLoadServiceBean",
           mappedName = "GeoLabsReportLoadServiceBean")
@Remote(GeoLabsReportLoadService.class)
@PortableWebService(targetNamespace = "/com/ceix/geolabs/model/services/common/",
                    serviceName = "GeoLabsReportLoadService", portName = "GeoLabsReportLoadServiceSoapHttpPort",
                    endpointInterface =
                    "com.ceix.geolabs.model.services.common.serviceinterface.GeoLabsReportLoadService")

public class GeoLabsReportLoadServiceImpl extends ServiceImpl implements GeoLabsReportLoadService {
    private static boolean _isInited = false;


    private static final Map _map = new HashMap();

    /**
     * This is the default constructor (do not remove).
     */
    public GeoLabsReportLoadServiceImpl() {
        init();
        setApplicationModuleDefName("com.ceix.geolabs.model.services.GeoLabsReportLoadAM");
        setConfigurationName("GeoLabsReportLoadService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (GeoLabsReportLoadServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("com/ceix/geolabs/model/services/common/serviceinterface/",
                                                "GeoLabsReportLoadService.xsd");
                _map.put("execute", GeoLabsReportLoadAMImpl.class.getMethod("execute", new Class[] { }));
                _map.put("executeItmann", GeoLabsReportLoadAMImpl.class.getMethod("executeItmann", new Class[] { }));
                _isInited = true;
            } catch (Throwable t) {
                ADFLogger.createADFLogger(Diagnostic.SERVINT_RT_LOGGER).severe(t);
            }
        }
    }


    /**
     * execute: generated method. Do not modify.
     */
    public List<WSResultPSDO> execute() throws ServiceException {
        return (List<WSResultPSDO>)invokeCustom((Method)_map.get("execute"),
                                                new Object[] { },
                                                new String[] { },
                                                WSResultPSDO.class, false);
    }


    /**
     * executeItmann: generated method. Do not modify.
     */
    public List<WSResultPSDO> executeItmann() throws ServiceException {
        return (List<WSResultPSDO>) invokeCustom((Method) _map.get("executeItmann"), new Object[] { }, new String[] { },
                                                 WSResultPSDO.class, false);
    }
}
