package com.ceix.geolabs.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 11 20:20:28 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CEIXStsRailSchedulesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CEIXStsRailSchedulesVOImpl() {
    }
}
