package com.ceix.waybill.model.services;


import com.ceix.waybill.model.services.webserviceclient.OrderDetailsResponseBean;
import com.ceix.waybill.model.services.webserviceclient.PoReceiptBean;
import com.ceix.waybill.model.services.webserviceclient.STSWebServices;
import com.ceix.waybill.model.views.CeixStsContractItemsVOImpl;
import com.ceix.waybill.model.views.CeixStsWaybillHdrVOImpl;
import com.ceix.waybill.model.views.CeixStsWaybillLinesVOImpl;
import com.ceix.waybill.model.views.CeixStsWaybillLinesVORowImpl;

import com.ceix.waybill.model.views.CeixStsWaybillSearchVOImpl;

import com.ceix.waybill.model.views.DestinationVOImpl;

import com.ceix.waybill.model.views.LoadOriginVOImpl;

import com.oracle.xmlns.apps.scm.fom.importorders.orderimportservice.OrderImportRequest;
import com.oracle.xmlns.apps.scm.fom.importorders.orderimportservice.OrderImportResponse;
import com.oracle.xmlns.apps.scm.inventory.materialtransactions.pendingtransactions.stagedinventorytransactionservicev2.StagedInventoryTransaction;
import com.oracle.xmlns.apps.scm.receiving.receiptsinterface.transactions.processorservicev2.StagedReceivingHeader;

import com.oracle.xmlns.apps.scm.shipping.shipconfirm.deliveries.shipmentlineservice.ShipmentLineInformation;

import com.oracle.xmlns.apps.scm.shipping.shipconfirm.deliveries.shipmentlineservice.UpdateShipmentLinesResponse;

import java.math.BigDecimal;

import java.util.List;

import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 31 19:03:55 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixStsWaybillAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CeixStsWaybillAMImpl() {
    }

    /**
     * Container's getter for CeixStsWaybillHdrVO1.
     * @return CeixStsWaybillHdrVO1
     */
    public ViewObjectImpl getCeixStsWaybillHdrVO1() {
        return (ViewObjectImpl)findViewObject("CeixStsWaybillHdrVO1");
    }

    /**
     * Container's getter for CeixStsWaybillLinesVO1.
     * @return CeixStsWaybillLinesVO1
     */
    public ViewObjectImpl getCeixStsWaybillLinesVO1() {
        return (ViewObjectImpl)findViewObject("CeixStsWaybillLinesVO1");
    }

    /**
     * Container's getter for CeixStsWaybillHdrVO2.
     * @return CeixStsWaybillHdrVO2
     */
    public ViewObjectImpl getCeixStsWaybillHdrVO2() {
        return (ViewObjectImpl)findViewObject("CeixStsWaybillHdrVO2");
    }

    /**
     * Container's getter for CeixStsWaybillLinesVO2.
     * @return CeixStsWaybillLinesVO2
     */
    public ViewObjectImpl getCeixStsWaybillLinesVO2() {
        return (ViewObjectImpl)findViewObject("CeixStsWaybillLinesVO2");
    }

    /**
     * Container's getter for CeixStsWaybillSearchVO1.
     * @return CeixStsWaybillSearchVO1
     */
    public CeixStsWaybillSearchVOImpl getCeixStsWaybillSearchVO1() {
        return (CeixStsWaybillSearchVOImpl) findViewObject("CeixStsWaybillSearchVO1");
    }

    /**
     * Container's getter for CeixStsWaybillBtmoreLinesFkLink1.
     * @return CeixStsWaybillBtmoreLinesFkLink1
     */
    public ViewLinkImpl getCeixStsWaybillBtmoreLinesFkLink1() {
        return (ViewLinkImpl)findViewLink("CeixStsWaybillBtmoreLinesFkLink1");
    }
    
    public String initVO(){
        ViewObject searchvo = getCeixStsWaybillSearchVO1();
        searchvo.reset();
        searchvo.clearCache();
        //searchvo.setNamedWhereClauseParam("pOrderNum", "kkll");
        searchvo.executeEmptyRowSet();
        ViewObject linevo = getCeixStsWaybillLinesVO1();
        linevo.reset();
        linevo.clearCache();
        //searchvo.setNamedWhereClauseParam("pOrderNum", "kkll");
        linevo.executeEmptyRowSet();
        return "start";
    }
    
    public void handleSelectCheckBox(boolean flag){
        int i=0;
        ViewObject vo = findViewObject("CeixStsWaybillLinesVO1");
        if (vo.getRowCount() > 0 )
        {
            vo.first();
            RowSetIterator rowItr = vo.createRowSetIterator(null);
            while (rowItr.hasNext()){
                CeixStsWaybillLinesVORowImpl tsRow = (CeixStsWaybillLinesVORowImpl) rowItr.next();
                if(tsRow.getShipmentNumber() == null){
                    //System.out.println("The shipment is :"+tsRow.getDumpSequence());
                    if(tsRow.getAttribute("ShipmentNumber") == null){
                        tsRow.setSelectFlag(flag); 
                    }                    
                }                
            }
            rowItr.closeRowSetIterator();
        }
    }
    
    public String  callPickWaveServiceImpl(String p_orderNo, String p_sourceSystemName, String p_shipFromOrganization, String p_orderType, String p_releaseRule ) { 
        String pickwaveNum = "";
        STSWebServices sTSWebServices = new STSWebServices();
        pickwaveNum = sTSWebServices.callPickWaveService(p_orderNo, p_sourceSystemName, p_shipFromOrganization, p_orderType, p_releaseRule);
        
        return pickwaveNum;
    }
    
    public String callProcessReleasePickBatchImpl(String pickBatch, String p_releaseMode){
        String pickRelease = "";
        STSWebServices sTSWebServices = new STSWebServices();
        pickRelease = sTSWebServices.callProcessReleasePickBatch(pickBatch, p_releaseMode);
        
        return pickRelease;
    }
    
    public String callRunReportImpl(String salesOrderNumbr) {
            //List<DeliveryDetails> delList = new ArrayList<DeliveryDetails>();
            String delLine = null;
            STSWebServices sTSWebServices = new STSWebServices();
            delLine = sTSWebServices.callRunReport(salesOrderNumbr);
            return delLine;
        }
    
    public String getLineStatusImpl(String salesOrderNumbr, String itemNumber) {
            //List<DeliveryDetails> delList = new ArrayList<DeliveryDetails>();
            String orderInfo = null;
            STSWebServices sTSWebServices = new STSWebServices();
            orderInfo = sTSWebServices.getLineStatus(salesOrderNumbr,itemNumber);
            return orderInfo;
        }
    
    public String callCreateShipmentRequestServiceImpl(String shipmentName, String shipFromOrganization,
                                                     String p_customerNumber,
                                                     String p_shipToPartySiteNumber,
                                                     String p_dumpdate, BigDecimal p_weightTons, String carrier){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        status = sTSWebServices.callProcessCreateUpdateShipmentService(shipmentName, 
                                                                       shipFromOrganization, p_customerNumber, 
                                                                    p_shipToPartySiteNumber, p_dumpdate, p_weightTons,carrier);
        return status;                                                     
    }
    
    public String callManageShipmentAssignmentsImpl(String shipmentName, Long shipmentLineNum){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        status = sTSWebServices.callManageShipmentAssignments(shipmentName, shipmentLineNum);
        return status;                                                     
    }
    
    public Long callSplitShipmentLineImpl(Long shipmentLineNum, BigDecimal weightTons){
        Long shipmentLineFromSplitLine = 0L;
        STSWebServices sTSWebServices = new STSWebServices();
        shipmentLineFromSplitLine = sTSWebServices.callSplitShipmentLine(shipmentLineNum, weightTons);
        return shipmentLineFromSplitLine;
    }
    
    public UpdateShipmentLinesResponse callUpdateShipmentLineImpl(List<ShipmentLineInformation> p_shipmentLineInformationList){
        UpdateShipmentLinesResponse updateShipmentLinesResponse = new UpdateShipmentLinesResponse();
        STSWebServices sTSWebServices = new STSWebServices();
        updateShipmentLinesResponse = sTSWebServices.callUpdateShipmentLine(p_shipmentLineInformationList);
        return updateShipmentLinesResponse;
    }
    
    public String callprocessShippingCostImpl(String p_cost, BigDecimal p_Amount, Long p_shipmentLineFromSplitLine){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        status = sTSWebServices.callprocessShippingCost(p_cost, p_Amount, p_shipmentLineFromSplitLine);
        return status;
    }
    
    public String callProcessShipmentActionImpl(String shipmentName,String shipConfirmRule){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        status = sTSWebServices.callProcessShipmentAction(shipmentName,shipConfirmRule);
        return status;
    }
    
    /*public OrderDetailsResponseBean callGetOrderDetailsImpl(String sourceTransSystem, String sourceTransNumber, String headItemNumber){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        OrderDetailsResponseBean orderDetailsResponseBean = sTSWebServices.callGetOrderDetails(sourceTransSystem,sourceTransNumber, headItemNumber);
        return orderDetailsResponseBean;
    }*/
    
    public String callProcessorImpl(StagedReceivingHeader stagedReceivingHeader){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        status = sTSWebServices.callProcessor(stagedReceivingHeader);
        return status;
    }
    
    public PoReceiptBean callGetPurchaseOrderDetailsImpl(String poNum, String legalEntityName){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        PoReceiptBean poReceiptBean = sTSWebServices.callGetPurchaseOrderDetails(poNum, legalEntityName);
        return poReceiptBean;
    }
    
    public String callinsertAndProcessInterfaceRowsImpl(List<StagedInventoryTransaction> stagedInventoryTransactionList){
        String status = null;
        STSWebServices sTSWebServices = new STSWebServices();
        status = sTSWebServices.callinsertAndProcessInterfaceRows(stagedInventoryTransactionList);
        return status;
    }

    /**
     * Container's getter for CeixStsWaybillBtmoreHdrDeleteTrainVo1.
     * @return CeixStsWaybillBtmoreHdrDeleteTrainVo1
     */
    public ViewObjectImpl getCeixStsWaybillBtmoreHdrDeleteTrainVo1() {
        return (ViewObjectImpl)findViewObject("CeixStsWaybillBtmoreHdrDeleteTrainVo1");
    }
    
    //Added Method -*-
    public OrderImportResponse callorderImportImpl(OrderImportRequest OrderImportDtls){
        OrderImportResponse orderImportResponse = new OrderImportResponse();
        STSWebServices sTSWebServices = new STSWebServices();
        orderImportResponse = sTSWebServices.callorderImport(OrderImportDtls);
        return orderImportResponse;
    }

    /**
     * Container's getter for CeixStsContractItemsVO1.
     * @return CeixStsContractItemsVO1
     */
    public CeixStsContractItemsVOImpl getCeixStsContractItemsVO1() {
        return (CeixStsContractItemsVOImpl) findViewObject("CeixStsContractItemsVO1");
    }

    /**
     * Container's getter for DestinationVO1.
     * @return DestinationVO1
     */
    public DestinationVOImpl getDestinationVO1() {
        return (DestinationVOImpl) findViewObject("DestinationVO1");
    }

    /**
     * Container's getter for LoadOriginVO1.
     * @return LoadOriginVO1
     */
    public LoadOriginVOImpl getLoadOriginVO1() {
        return (LoadOriginVOImpl) findViewObject("LoadOriginVO1");
    }
}
