package ceix.com.bc.am;


import ceix.com.bc.pojo.ShippingNotification;
import ceix.com.bc.views.CeixDeliveryLinesVOImpl;

import com.itextpdf.text.DocumentException;

import java.io.FileNotFoundException;
import java.io.IOException;

import java.net.MalformedURLException;

import java.text.ParseException;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.client.Configuration;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 22 15:30:31 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CEIXShipNotificationAMImpl extends ApplicationModuleImpl {
    
    
    
    /**
     * This is the default constructor (do not remove).
     */
    public CEIXShipNotificationAMImpl() {
    }
    
     
    
    public String createPDFReport(String trainNumber){
        
        RowSetIterator headerRowSetIter = null;
        RowSetIterator lineRowSetIter = null;
        
 
        String amDef = "ceix.com.bc.am.CEIXShipNotificationAM";
        String config = "CEIXShipNotificationAMLocal";
        String fileName = null;

        CEIXShipNotificationAMImpl am;
        am = (CEIXShipNotificationAMImpl) Configuration.createRootApplicationModule(amDef, config);
        ViewObject header = am.getCeixDeliveryHeadersVO1(); 
        header.setWhereClause("UNIT_TRAIN_NUMBER ='" + trainNumber + "'"); 
        header.executeQuery();
        
        System.out.println("Query:" + header.getQuery());
         
        ViewObject line = am.getCeixDeliveryLinesVO1(); 
        line.setWhereClause("UNIT_TRAIN_NUMBER ='" + trainNumber + "'"); 
        line.executeQuery();
        RowSetIterator iter = line.createRowSetIterator(null);

double totalTons=0;
        while (iter.hasNext()) {
            Row row = iter.next();
            String weightInTons = "";
            if (row.getAttribute("WeightInTons") != null)
                weightInTons = row.getAttribute("WeightInTons").toString();
            totalTons = totalTons + Double.valueOf(weightInTons);   
        }
       
        System.out.println("totalTons:" +totalTons);
        
        ShippingNotification obj = new ShippingNotification();
        try {
            obj.createPDFInternal(header, line, trainNumber);
        } catch (FileNotFoundException e) {
        } catch (MalformedURLException e) {
        } catch (IOException e) {
        } catch (ParseException e) {
        } catch (DocumentException e) {
        } catch (Exception e) {
        }

        /*
        ViewObjectImpl headerVOImpl = this.getCeixDeliveryHeadersVO1();
        headerVOImpl.setWhereClause("UNIT_TRAIN_NUMBER ='" + trainNumber + "'");
        headerVOImpl.executeQuery();
        headerRowSetIter = headerVOImpl.createRowSetIterator(null);
        headerRowSetIter.reset();

        ViewObjectImpl lineVOImpl = this.getCeixDeliveryLinesVO1();
        lineVOImpl.setWhereClause("UNIT_TRAIN_NUMBER ='" + trainNumber + "'");
        lineVOImpl.executeQuery();
        lineRowSetIter = lineVOImpl.createRowSetIterator(null);
        lineRowSetIter.reset();
        */
        
        trainNumber = "E666";
        return trainNumber;
    }
    
    public static void main(String[] args) throws DocumentException, ParseException, IOException, MalformedURLException,
                                                  FileNotFoundException, Exception {
        CEIXShipNotificationAMImpl obj = new CEIXShipNotificationAMImpl();
        String fileName = obj.createPDFReport("E666");
        double totalTons = 123.3456789;
        System.out.println("Rounded:"+ Math.round(totalTons)); 
        System.out.println("Rounded 2 decimal:"+ Math.round(totalTons * 100D)/100D); 
       
        
        

    }


    /**
     * Container's getter for CeixDeliveryHeadersVO1.
     * @return CeixDeliveryHeadersVO1
     */
    public ViewObjectImpl getCeixDeliveryHeadersVO1() {
        return (ViewObjectImpl) findViewObject("CeixDeliveryHeadersVO1");
    }

    /**
     * Container's getter for CeixDeliveryLinesVO1.
     * @return CeixDeliveryLinesVO1
     */
    public CeixDeliveryLinesVOImpl getCeixDeliveryLinesVO1() {
        return (CeixDeliveryLinesVOImpl) findViewObject("CeixDeliveryLinesVO1");
    }
}

