package com.ceix.qualnetxmlgen.model.services;


import com.ceix.qualnetxmlgen.model.services.common.CEIXQualnetXMLGenAM;
import com.ceix.qualnetxmlgen.model.view.QualityMetricsReportVOImpl;
import com.ceix.qualnetxmlgen.model.view.WSResultPVOImpl;
import com.ceix.qualnetxmlgen.xmlbuilder.QualnetXMLGenerator;

import java.text.SimpleDateFormat;

import java.util.Date;
import java.util.List;
import java.util.logging.Level;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 15 16:31:49 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CEIXQualnetXMLGenAMImpl extends ApplicationModuleImpl implements CEIXQualnetXMLGenAM {
    
    ADFLogger _logger = ADFLogger.createADFLogger(CEIXQualnetXMLGenAMImpl.class);
    
    /**
     * This is the default constructor (do not remove).
     */
    public CEIXQualnetXMLGenAMImpl() {
    }

    public List<ViewRowImpl> generateQualnetQualityReport() {
        
        _logger.log(Level.FINER, ">>generateQualnetQualityReport");
              
        final String ftpOutDir = "CEIX_OracleERP/INTF/Outbound/OM/Qualnet/Out";
        final String ftpDir = "CEIX_OracleERP/INTF/Outbound/OM/Qualnet/Archive";
        
        final String timeStamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        
        final String ftpOutFileName = "quality_metrics.xml";
        final String ftpFileName = "quality_metrics_" + timeStamp + ".xml";
        
        final boolean isDev = false;
        
        final ViewObjectImpl voData = (ViewObjectImpl)this.getQualityMetricsReport1();
        final WSResultPVOImpl resultVo = this.getWSResultP1();
        
        final QualnetXMLGenerator genOut = new QualnetXMLGenerator(voData, ftpOutDir, ftpOutFileName, isDev, resultVo);
        final QualnetXMLGenerator gen = new QualnetXMLGenerator(voData, ftpDir, ftpFileName, isDev, resultVo);
        
        final List<ViewRowImpl> lstResult = (List<ViewRowImpl>)gen.generate();
        final List<ViewRowImpl> lstOutResult = (List<ViewRowImpl>)genOut.generate();
        
        _logger.log(Level.FINER, "<<generateQualnetQualityReport");
        return lstOutResult;

    }
    
    public List<ViewRowImpl> generateQualnetSTSRailScheduleReport() {
        
        _logger.log(Level.FINER, ">>generateQualnetSTSRailScheduleReport");        
        
            final String ftpOutDir = "CEIX_OracleERP/INTF/Outbound/OM/Qualnet/Out";
            final String ftpDir = "CEIX_OracleERP/INTF/Outbound/OM/Qualnet/Archive";
            
            final String timeStamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
            
            final String ftpOutFileName = "sts_rail_schedules.xml";
            final String ftpFileName = "sts_rail_schedules_" + timeStamp + ".xml";
            
            final boolean isDev = false;
            
            final ViewObjectImpl voData = this.getRailSchedulesReportCustomVO();
            final WSResultPVOImpl resultVo = this.getWSResultP1();
            
            final QualnetXMLGenerator gen = new QualnetXMLGenerator(voData, ftpDir, ftpFileName, isDev, resultVo);
            final QualnetXMLGenerator genOut = new QualnetXMLGenerator(voData, ftpOutDir, ftpOutFileName, isDev, resultVo);
            
            final List<ViewRowImpl> lstResult = (List<ViewRowImpl>)gen.generate();
            final List<ViewRowImpl> lstOutResult = (List<ViewRowImpl>)genOut.generate();
        
        try
        {
            voData.remove();
        }
        catch(Exception e) {
            _logger.severe("Error while removing custom VO.",e);
        }
        
        _logger.log(Level.FINER, "<<generateQualnetSTSRailScheduleReport");
        return lstOutResult;

    }
    
    public ViewObjectImpl getRailSchedulesReportCustomVO() {
        
        ViewObjectImpl vo = (ViewObjectImpl)
            this.createViewObjectFromQueryStmt("CEIXStsRailSchedulesVO", "SELECT * FROM CEIX_VW_QUALNT_RAILSCH_XML");
        short fetchSize = 200;
        vo.setFetchSize(fetchSize);
        vo.executeQuery();
        return vo;
        
    }


    /**
     * Container's getter for WSResultP1.
     * @return WSResultP1
     */
    public WSResultPVOImpl getWSResultP1() {
        return (WSResultPVOImpl)findViewObject("WSResultP1");
    }

    /**
     * Container's getter for QualityMetricsReport1.
     * @return QualityMetricsReport1
     */
    public QualityMetricsReportVOImpl getQualityMetricsReport1() {
        return (QualityMetricsReportVOImpl)findViewObject("QualityMetricsReport1");
    }
}
