package com.ceix.delivery.model.views;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 21 21:13:04 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixStsWaybillBtmoreHdrViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CeixStsWaybillBtmoreHdrViewImpl() {
    }
}
