package com.ceix.delivery.model.views;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 21 21:16:28 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CeixStsWaybillBtmoreLinesViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_CEIXSTSWAYBILLBTMORELINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DeliveryLineId {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getDeliveryLineId();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setDeliveryLineId((Number) value);
            }
        }
        ,
        ShipToInformation {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getShipToInformation();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setShipToInformation((String) value);
            }
        }
        ,
        DumpSequence {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getDumpSequence();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setDumpSequence((Number) value);
            }
        }
        ,
        RailRoad {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getRailRoad();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setRailRoad((String) value);
            }
        }
        ,
        CarPrefix {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getCarPrefix();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setCarPrefix((String) value);
            }
        }
        ,
        CarNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getCarNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setCarNumber((String) value);
            }
        }
        ,
        CarWeight {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getCarWeight();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setCarWeight((String) value);
            }
        }
        ,
        Type {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getType();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setType((String) value);
            }
        }
        ,
        Uom {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getUom();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setUom((String) value);
            }
        }
        ,
        TrainNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getTrainNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setTrainNumber((String) value);
            }
        }
        ,
        DeliveryHeaderId {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getDeliveryHeaderId();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setDeliveryHeaderId((Number) value);
            }
        }
        ,
        SalesOrderNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getSalesOrderNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setSalesOrderNumber((String) value);
            }
        }
        ,
        NewTrainNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getNewTrainNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setNewTrainNumber((String) value);
            }
        }
        ,
        NewCarPrefix {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getNewCarPrefix();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setNewCarPrefix((String) value);
            }
        }
        ,
        NewCarNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getNewCarNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setNewCarNumber((String) value);
            }
        }
        ,
        ScheduleDate {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getScheduleDate();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setScheduleDate((Date) value);
            }
        }
        ,
        ShipmentNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getShipmentNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setShipmentNumber((String) value);
            }
        }
        ,
        ShippedQuantity {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getShippedQuantity();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setShippedQuantity((String) value);
            }
        }
        ,
        FreightCost {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getFreightCost();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setFreightCost((String) value);
            }
        }
        ,
        CreationDate {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getCreationDate();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreatedBy {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdateDate {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WeightInTons {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getWeightInTons();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setWeightInTons((String) value);
            }
        }
        ,
        ProcessedFlag {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getProcessedFlag();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setProcessedFlag((String) value);
            }
        }
        ,
        TransferredFlag {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getTransferredFlag();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setTransferredFlag((String) value);
            }
        }
        ,
        Comments {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getComments();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setComments((String) value);
            }
        }
        ,
        SubInventory {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getSubInventory();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setSubInventory((String) value);
            }
        }
        ,
        SONUMBER {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getSONUMBER();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setSONUMBER((String) value);
            }
        }
        ,
        ItemNumber {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getItemNumber();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setItemNumber((String) value);
            }
        }
        ,
        Destination {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getDestination();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setDestination((String) value);
            }
        }
        ,
        LoadOrigin {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getLoadOrigin();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setLoadOrigin((String) value);
            }
        }
        ,
        Straggler {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getStraggler();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setStraggler((String) value);
            }
        }
        ,
        Freight {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getFreight();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setFreight((String) value);
            }
        }
        ,
        DumpedTons {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getDumpedTons();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setDumpedTons((String) value);
            }
        }
        ,
        DumpWeight {
            protected Object get(CeixStsWaybillBtmoreLinesViewRowImpl obj) {
                return obj.getDumpWeight();
            }

            protected void put(CeixStsWaybillBtmoreLinesViewRowImpl obj, Object value) {
                obj.setDumpWeight((String) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;


        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(CeixStsWaybillBtmoreLinesViewRowImpl object);

        protected abstract void put(CeixStsWaybillBtmoreLinesViewRowImpl object, Object value);
    }


    public static final int DELIVERYLINEID = AttributesEnum.DeliveryLineId.index();
    public static final int SHIPTOINFORMATION = AttributesEnum.ShipToInformation.index();
    public static final int DUMPSEQUENCE = AttributesEnum.DumpSequence.index();
    public static final int RAILROAD = AttributesEnum.RailRoad.index();
    public static final int CARPREFIX = AttributesEnum.CarPrefix.index();
    public static final int CARNUMBER = AttributesEnum.CarNumber.index();
    public static final int CARWEIGHT = AttributesEnum.CarWeight.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int TRAINNUMBER = AttributesEnum.TrainNumber.index();
    public static final int DELIVERYHEADERID = AttributesEnum.DeliveryHeaderId.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int NEWTRAINNUMBER = AttributesEnum.NewTrainNumber.index();
    public static final int NEWCARPREFIX = AttributesEnum.NewCarPrefix.index();
    public static final int NEWCARNUMBER = AttributesEnum.NewCarNumber.index();
    public static final int SCHEDULEDATE = AttributesEnum.ScheduleDate.index();
    public static final int SHIPMENTNUMBER = AttributesEnum.ShipmentNumber.index();
    public static final int SHIPPEDQUANTITY = AttributesEnum.ShippedQuantity.index();
    public static final int FREIGHTCOST = AttributesEnum.FreightCost.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int WEIGHTINTONS = AttributesEnum.WeightInTons.index();
    public static final int PROCESSEDFLAG = AttributesEnum.ProcessedFlag.index();
    public static final int TRANSFERREDFLAG = AttributesEnum.TransferredFlag.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int SUBINVENTORY = AttributesEnum.SubInventory.index();
    public static final int SONUMBER = AttributesEnum.SONUMBER.index();
    public static final int ITEMNUMBER = AttributesEnum.ItemNumber.index();
    public static final int DESTINATION = AttributesEnum.Destination.index();
    public static final int LOADORIGIN = AttributesEnum.LoadOrigin.index();
    public static final int STRAGGLER = AttributesEnum.Straggler.index();
    public static final int FREIGHT = AttributesEnum.Freight.index();
    public static final int DUMPEDTONS = AttributesEnum.DumpedTons.index();
    public static final int DUMPWEIGHT = AttributesEnum.DumpWeight.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CeixStsWaybillBtmoreLinesViewRowImpl() {
    }

    /**
     * Gets CeixStsWaybillBtmoreLines entity object.
     * @return the CeixStsWaybillBtmoreLines
     */
    public EntityImpl getCeixStsWaybillBtmoreLines() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DELIVERY_LINE_ID using the alias name DeliveryLineId.
     * @return the DELIVERY_LINE_ID
     */
    public Number getDeliveryLineId() {
        return (Number) getAttributeInternal(DELIVERYLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_LINE_ID using the alias name DeliveryLineId.
     * @param value value to set the DELIVERY_LINE_ID
     */
    public void setDeliveryLineId(Number value) {
        setAttributeInternal(DELIVERYLINEID, value);
    }

    /**
     * Gets the attribute value for SHIP_TO_INFORMATION using the alias name ShipToInformation.
     * @return the SHIP_TO_INFORMATION
     */
    public String getShipToInformation() {
        return (String) getAttributeInternal(SHIPTOINFORMATION);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TO_INFORMATION using the alias name ShipToInformation.
     * @param value value to set the SHIP_TO_INFORMATION
     */
    public void setShipToInformation(String value) {
        setAttributeInternal(SHIPTOINFORMATION, value);
    }

    /**
     * Gets the attribute value for DUMP_SEQUENCE using the alias name DumpSequence.
     * @return the DUMP_SEQUENCE
     */
    public Number getDumpSequence() {
        return (Number) getAttributeInternal(DUMPSEQUENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUMP_SEQUENCE using the alias name DumpSequence.
     * @param value value to set the DUMP_SEQUENCE
     */
    public void setDumpSequence(Number value) {
        setAttributeInternal(DUMPSEQUENCE, value);
    }

    /**
     * Gets the attribute value for RAIL_ROAD using the alias name RailRoad.
     * @return the RAIL_ROAD
     */
    public String getRailRoad() {
        return (String) getAttributeInternal(RAILROAD);
    }

    /**
     * Sets <code>value</code> as attribute value for RAIL_ROAD using the alias name RailRoad.
     * @param value value to set the RAIL_ROAD
     */
    public void setRailRoad(String value) {
        setAttributeInternal(RAILROAD, value);
    }

    /**
     * Gets the attribute value for CAR_PREFIX using the alias name CarPrefix.
     * @return the CAR_PREFIX
     */
    public String getCarPrefix() {
        return (String) getAttributeInternal(CARPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_PREFIX using the alias name CarPrefix.
     * @param value value to set the CAR_PREFIX
     */
    public void setCarPrefix(String value) {
        setAttributeInternal(CARPREFIX, value);
    }

    /**
     * Gets the attribute value for CAR_NUMBER using the alias name CarNumber.
     * @return the CAR_NUMBER
     */
    public String getCarNumber() {
        return (String) getAttributeInternal(CARNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_NUMBER using the alias name CarNumber.
     * @param value value to set the CAR_NUMBER
     */
    public void setCarNumber(String value) {
        setAttributeInternal(CARNUMBER, value);
    }

    /**
     * Gets the attribute value for CAR_WEIGHT using the alias name CarWeight.
     * @return the CAR_WEIGHT
     */
    public String getCarWeight() {
        return (String) getAttributeInternal(CARWEIGHT);
    }

    /**
     * Sets <code>value</code> as attribute value for CAR_WEIGHT using the alias name CarWeight.
     * @param value value to set the CAR_WEIGHT
     */
    public void setCarWeight(String value) {
        setAttributeInternal(CARWEIGHT, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for TRAIN_NUMBER using the alias name TrainNumber.
     * @return the TRAIN_NUMBER
     */
    public String getTrainNumber() {
        return (String) getAttributeInternal(TRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAIN_NUMBER using the alias name TrainNumber.
     * @param value value to set the TRAIN_NUMBER
     */
    public void setTrainNumber(String value) {
        setAttributeInternal(TRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for DELIVERY_HEADER_ID using the alias name DeliveryHeaderId.
     * @return the DELIVERY_HEADER_ID
     */
    public Number getDeliveryHeaderId() {
        return (Number) getAttributeInternal(DELIVERYHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_HEADER_ID using the alias name DeliveryHeaderId.
     * @param value value to set the DELIVERY_HEADER_ID
     */
    public void setDeliveryHeaderId(Number value) {
        setAttributeInternal(DELIVERYHEADERID, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @return the SALES_ORDER_NUMBER
     */
    public String getSalesOrderNumber() {
        return (String) getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @param value value to set the SALES_ORDER_NUMBER
     */
    public void setSalesOrderNumber(String value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for NEW_TRAIN_NUMBER using the alias name NewTrainNumber.
     * @return the NEW_TRAIN_NUMBER
     */
    public String getNewTrainNumber() {
        return (String) getAttributeInternal(NEWTRAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_TRAIN_NUMBER using the alias name NewTrainNumber.
     * @param value value to set the NEW_TRAIN_NUMBER
     */
    public void setNewTrainNumber(String value) {
        setAttributeInternal(NEWTRAINNUMBER, value);
    }

    /**
     * Gets the attribute value for NEW_CAR_PREFIX using the alias name NewCarPrefix.
     * @return the NEW_CAR_PREFIX
     */
    public String getNewCarPrefix() {
        return (String) getAttributeInternal(NEWCARPREFIX);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_CAR_PREFIX using the alias name NewCarPrefix.
     * @param value value to set the NEW_CAR_PREFIX
     */
    public void setNewCarPrefix(String value) {
        setAttributeInternal(NEWCARPREFIX, value);
    }

    /**
     * Gets the attribute value for NEW_CAR_NUMBER using the alias name NewCarNumber.
     * @return the NEW_CAR_NUMBER
     */
    public String getNewCarNumber() {
        return (String) getAttributeInternal(NEWCARNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_CAR_NUMBER using the alias name NewCarNumber.
     * @param value value to set the NEW_CAR_NUMBER
     */
    public void setNewCarNumber(String value) {
        setAttributeInternal(NEWCARNUMBER, value);
    }

    /**
     * Gets the attribute value for SCHEDULE_DATE using the alias name ScheduleDate.
     * @return the SCHEDULE_DATE
     */
    public Date getScheduleDate() {
        return (Date) getAttributeInternal(SCHEDULEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEDULE_DATE using the alias name ScheduleDate.
     * @param value value to set the SCHEDULE_DATE
     */
    public void setScheduleDate(Date value) {
        setAttributeInternal(SCHEDULEDATE, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber.
     * @return the SHIPMENT_NUMBER
     */
    public String getShipmentNumber() {
        return (String) getAttributeInternal(SHIPMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber.
     * @param value value to set the SHIPMENT_NUMBER
     */
    public void setShipmentNumber(String value) {
        setAttributeInternal(SHIPMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for SHIPPED_QUANTITY using the alias name ShippedQuantity.
     * @return the SHIPPED_QUANTITY
     */
    public String getShippedQuantity() {
        return (String) getAttributeInternal(SHIPPEDQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPPED_QUANTITY using the alias name ShippedQuantity.
     * @param value value to set the SHIPPED_QUANTITY
     */
    public void setShippedQuantity(String value) {
        setAttributeInternal(SHIPPEDQUANTITY, value);
    }

    /**
     * Gets the attribute value for FREIGHT_COST using the alias name FreightCost.
     * @return the FREIGHT_COST
     */
    public String getFreightCost() {
        return (String) getAttributeInternal(FREIGHTCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for FREIGHT_COST using the alias name FreightCost.
     * @param value value to set the FREIGHT_COST
     */
    public void setFreightCost(String value) {
        setAttributeInternal(FREIGHTCOST, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }


    /**
     * Gets the attribute value for WEIGHT_IN_TONS using the alias name WeightInTons.
     * @return the WEIGHT_IN_TONS
     */
    public String getWeightInTons() {
        return (String) getAttributeInternal(WEIGHTINTONS);
    }

    /**
     * Sets <code>value</code> as attribute value for WEIGHT_IN_TONS using the alias name WeightInTons.
     * @param value value to set the WEIGHT_IN_TONS
     */
    public void setWeightInTons(String value) {
        setAttributeInternal(WEIGHTINTONS, value);
    }

    /**
     * Gets the attribute value for PROCESSED_FLAG using the alias name ProcessedFlag.
     * @return the PROCESSED_FLAG
     */
    public String getProcessedFlag() {
        return (String) getAttributeInternal(PROCESSEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESSED_FLAG using the alias name ProcessedFlag.
     * @param value value to set the PROCESSED_FLAG
     */
    public void setProcessedFlag(String value) {
        setAttributeInternal(PROCESSEDFLAG, value);
    }

    /**
     * Gets the attribute value for TRANSFERRED_FLAG using the alias name TransferredFlag.
     * @return the TRANSFERRED_FLAG
     */
    public String getTransferredFlag() {
        return (String) getAttributeInternal(TRANSFERREDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFERRED_FLAG using the alias name TransferredFlag.
     * @param value value to set the TRANSFERRED_FLAG
     */
    public void setTransferredFlag(String value) {
        setAttributeInternal(TRANSFERREDFLAG, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for SUB_INVENTORY using the alias name SubInventory.
     * @return the SUB_INVENTORY
     */
    public String getSubInventory() {
        return (String) getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_INVENTORY using the alias name SubInventory.
     * @param value value to set the SUB_INVENTORY
     */
    public void setSubInventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getSONUMBER() {
        return (String) getAttributeInternal(SONUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setSONUMBER(String value) {
        setAttributeInternal(SONUMBER, value);
    }


    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getItemNumber() {
        return (String) getAttributeInternal(ITEMNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setItemNumber(String value) {
        setAttributeInternal(ITEMNUMBER, value);
    }

    /**
     * Gets the attribute value for DESTINATION using the alias name Destination.
     * @return the DESTINATION
     */
    public String getDestination() {
        return (String) getAttributeInternal(DESTINATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION using the alias name Destination.
     * @param value value to set the DESTINATION
     */
    public void setDestination(String value) {
        setAttributeInternal(DESTINATION, value);
    }

    /**
     * Gets the attribute value for LOAD_ORIGIN using the alias name LoadOrigin.
     * @return the LOAD_ORIGIN
     */
    public String getLoadOrigin() {
        return (String) getAttributeInternal(LOADORIGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAD_ORIGIN using the alias name LoadOrigin.
     * @param value value to set the LOAD_ORIGIN
     */
    public void setLoadOrigin(String value) {
        setAttributeInternal(LOADORIGIN, value);
    }

    /**
     * Gets the attribute value for STRAGGLER using the alias name Straggler.
     * @return the STRAGGLER
     */
    public String getStraggler() {
        return (String) getAttributeInternal(STRAGGLER);
    }

    /**
     * Sets <code>value</code> as attribute value for STRAGGLER using the alias name Straggler.
     * @param value value to set the STRAGGLER
     */
    public void setStraggler(String value) {
        setAttributeInternal(STRAGGLER, value);
    }

    /**
     * Gets the attribute value for FREIGHT using the alias name Freight.
     * @return the FREIGHT
     */
    public String getFreight() {
        return (String) getAttributeInternal(FREIGHT);
    }

    /**
     * Sets <code>value</code> as attribute value for FREIGHT using the alias name Freight.
     * @param value value to set the FREIGHT
     */
    public void setFreight(String value) {
        setAttributeInternal(FREIGHT, value);
    }

    /**
     * Gets the attribute value for DUMPED_TONS using the alias name DumpedTons.
     * @return the DUMPED_TONS
     */
    public String getDumpedTons() {
        return (String) getAttributeInternal(DUMPEDTONS);
    }

    /**
     * Sets <code>value</code> as attribute value for DUMPED_TONS using the alias name DumpedTons.
     * @param value value to set the DUMPED_TONS
     */
    public void setDumpedTons(String value) {
        setAttributeInternal(DUMPEDTONS, value);
    }

    /**
     * Gets the attribute value for DUMP_WEIGHT using the alias name DumpWeight.
     * @return the DUMP_WEIGHT
     */
    public String getDumpWeight() {
        return (String) getAttributeInternal(DUMPWEIGHT);
    }

    /**
     * Sets <code>value</code> as attribute value for DUMP_WEIGHT using the alias name DumpWeight.
     * @param value value to set the DUMP_WEIGHT
     */
    public void setDumpWeight(String value) {
        setAttributeInternal(DUMPWEIGHT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
