package com.ceix.qualnetxmlgen.model.services.common.serviceinterface;

import com.ceix.qualnetxmlgen.model.view.common.WSResultPSDO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 15 16:46:53 IST 2018
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/com/ceix/qualnetxmlgen/model/services/common/",
    name="CEIXQualnetXMLGenService", wsdlLocation="com/ceix/qualnetxmlgen/model/services/common/serviceinterface/CEIXQualnetXMLGenService.wsdl")
@SDODatabinding(schemaLocation="com/ceix/qualnetxmlgen/model/services/common/serviceinterface/CEIXQualnetXMLGenService.xsd")
public interface CEIXQualnetXMLGenService {


    public static final String NAME = "{/com/ceix/qualnetxmlgen/model/services/common/}CEIXQualnetXMLGenService";

    /**
     * Exported method generateQualnetQualityReport from CEIXQualnetXMLGenAM.
     */
    @WebMethod(action="/com/ceix/qualnetxmlgen/model/services/common/generateQualnetQualityReport",
        operationName="generateQualnetQualityReport")
    @RequestWrapper(targetNamespace="/com/ceix/qualnetxmlgen/model/services/common/types/",
        localName="generateQualnetQualityReport")
    @ResponseWrapper(targetNamespace="/com/ceix/qualnetxmlgen/model/services/common/types/",
        localName="generateQualnetQualityReportResponse")
    @WebResult(name="result")
    List<WSResultPSDO> generateQualnetQualityReport() throws ServiceException;

    /**
     * Exported method generateQualnetSTSRailScheduleReport from CEIXQualnetXMLGenAM.
     */
    @WebMethod(action="/com/ceix/qualnetxmlgen/model/services/common/generateQualnetSTSRailScheduleReport",
        operationName="generateQualnetSTSRailScheduleReport")
    @RequestWrapper(targetNamespace="/com/ceix/qualnetxmlgen/model/services/common/types/",
        localName="generateQualnetSTSRailScheduleReport")
    @ResponseWrapper(targetNamespace="/com/ceix/qualnetxmlgen/model/services/common/types/",
        localName="generateQualnetSTSRailScheduleReportResponse")
    @WebResult(name="result")
    List<WSResultPSDO> generateQualnetSTSRailScheduleReport() throws ServiceException;
}
